### ISSUE TITLE
Blank space below the Top contributor section 

### ISSUE THREAD

**Issue by Ketanop321** [SUGAM-ARORA/UniCollab#102]
**Describe the bug**
![Screenshot 2024-05-20 182737](https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/3b8758b6-a58b-4aad-a38c-7c3e55433d51)

If i scroll down ,there is lot of blank space left below the top contributor 

In that left space there should be feed

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 Your image is not visible. Kindly share again

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 Issue assigned to you
