### ISSUE TITLE
Hover Background Color Alignment Issue on 'Source Code' Button

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#104]
**Describe the bug**
When hovering over the "Source Code" button, a white background appears, which negatively impacts the visual appearance.

**To Reproduce**
1.  Go to the "Read More" and "Source Code" buttons on the cards.
2.  Hover over these buttons.
3.  Observe the white background that appears on hover.

**Expected behavior**
The background color when hovering should either match the card's background color or be replaced with a color that fits the overall design better.

**Video**

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/bdcc0850-cf5d-4868-97fe-c38eee069194

**Additional context**
I am a GSSoC contributor and would like to address this issue. Kindly label this issue and assign it to me.

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
