### ISSUE TITLE
[FEATURE] Add Tooltips to Sidebar Icons

### ISSUE THREAD

**Issue by yashmandi** [SUGAM-ARORA/UniCollab#106]
### Summary:
Implement tooltips for sidebar icons to improve user navigation by displaying the name of the icon or function on hover.

### Description:
Currently, when users hover over icons in the sidebar, no additional information is provided. This can make it challenging, especially for new users, to understand the purpose of each icon. To enhance the user experience and improve navigation, I propose adding tooltips that display the name of the icon or its function when users hover over it.

### Example:
When hovering over the settings icon, a tooltip with the text "Settings" should appear.

I would like to work on this feature. Request you to assign this task to me

**Comment by SUGAM-ARORA** [comment]
@yashmandi Issue assigned to you

**Comment by yashmandi** [comment]
Can you please let me know what each icons resembels, i only know some of them.
![sidebar](https://github.com/SUGAM-ARORA/UniCollab/assets/132436131/2e520f0d-2c71-4d06-a994-46b4df8f5c2a)
