### ISSUE TITLE
Adding Animations

### ISSUE THREAD

**Issue by MHusain22** [SUGAM-ARORA/UniCollab#111]
**Is your feature request related to a problem? Please describe.**
Adding animations will make the UI look more enhanced and attractive.

**Describe the solution you'd like**
I can Add animations to the Page on loading and scrolling just like in my portfolio website https://mhportfolio.vercel.app/. Please assign me this to add new feature.

**Describe alternatives you've considered**
Using vanilla CSS and animations library the feature can be implemented.

**Additional context**
you can visit my website https://mhportfolio.vercel.app/ and my open source contribution website https://www.devlabsstore.tech/ to see animations.
@SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
Merged
