### ISSUE TITLE
Alignment Issue

### ISSUE THREAD

**Issue by SUGAM-ARORA** [SUGAM-ARORA/UniCollab#113]
While fixing notification section , the dropdown has been shifted to right making alignment issue .

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/96546088/cddcde86-9824-4c4a-a08b-69018d746abb)

**Comment by SeanAverS** [comment]
Hello. I would like to work on this. Could I please get assigned? Thank you.

**Comment by SUGAM-ARORA** [comment]
@SeanAverS Issue assigned to you
