### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by JeanPasquini** [SUGAM-ARORA/UniCollab#115]
_**Bootstrap Library**_

Bootstrap has supports with dark mode and you can add in your project. Link (https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode). It's so easy to use, in this document have all ways to use the dark-mode, you can find your alternative and use how you want.

------------------

_**Add library in your project**_

Only thing you need to do is download to add in your project or you can reference into head the link for library, but all this is write in website (https://getbootstrap.com/).

**_Download into project:_**

```
npm install bootstrap@5.3.3
```

-------------------

_**Observation**_
It's important to see what is the best for your project, it's only an ideia.

**Comment by SUGAM-ARORA** [comment]
@JeanPasquini Issue already exists #20
