### ISSUE TITLE
User Options Appear on Scroll(with White Background) Instead of Click

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#122]
**Describe the bug**
When scrolling to the right, a white background containing user information options appears.

**To Reproduce**
1. Scroll the horizontal bar to the right.
2. Observe the white background.

**Screenshots**
![BackgroundIssue](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/df7624e2-8b26-4426-90ef-2b1ce4de9e32)

**Expected behavior**
The user's information should only be displayed when the user clicks on their name, not when scrolling to the right.
![Solution](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/6022d453-b729-4f95-9ec9-a530d4dcbb5a)

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue already exists #113

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA I see that the issue has still not been solved. Kindly assign me this issue and I will resolve this issue as soon as possible.

Thank You!

**Comment by SUGAM-ARORA** [comment]
Work already done
