### ISSUE TITLE
Preloader 

### ISSUE THREAD

**Issue by Jagpreet153** [SUGAM-ARORA/UniCollab#128]
**Is your feature request related to a problem? Please describe.**
Yes. I would be adding a preloader to the site matching with the UI to increase the interest of user

**Describe the solution you'd like**
The preloader will be in svg with added css and would be displayed until the site loads totally

**Describe alternatives you've considered**
It would be done using useEffect and setTimeout functions

**Additional context**
Kindly assign this task to me under GSSoC'24

**Comment by SUGAM-ARORA** [comment]
@Jagpreet153 Issue assigned to you

**Comment by Jagpreet153** [comment]
@SUGAM-ARORA  Is this preloader OK ? 


https://github.com/SUGAM-ARORA/UniCollab/assets/119691733/efc37c37-5388-4ccf-9747-c5f09736da41

**Comment by SUGAM-ARORA** [comment]
Merged
