### ISSUE TITLE
404 page 

### ISSUE THREAD

**Issue by Jagpreet153** [SUGAM-ARORA/UniCollab#130]
**Is your feature request related to a problem? Please describe.**
Yes, I would be adding a 404 page corresponding the UI of site

**Describe the solution you'd like**
It would be a simple js file with added css

**Describe alternatives you've considered**
It would be called when none of the routes matches 

**Additional context**
Kindly assign this issue to me under GSSoC'24

**Comment by SUGAM-ARORA** [comment]
@Jagpreet153 You are already assigned an issue.

**Comment by SUGAM-ARORA** [comment]
#128

**Comment by Jagpreet153** [comment]
Ok @SUGAM-ARORA assign this issue once I complete the previous one

**Comment by nishant0708** [comment]
can you assign me this issue to me under gssoc 24.

**Comment by Jagpreet153** [comment]
@SUGAM-ARORA Kindly assign this issue to me . I have completed issue #128

**Comment by Jagpreet153** [comment]
@SUGAM-ARORA Please give updates regarding the issue

**Comment by SUGAM-ARORA** [comment]
@Jagpreet153 Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged
