### ISSUE TITLE
Notification message is hidden 

### ISSUE THREAD

**Issue by Ketanop321** [SUGAM-ARORA/UniCollab#133]
**Describe the bug**
Notification message is not visible as it is behind the main container
**To Reproduce**
1. Go to 'Notification bell'
2. Click on '.on it'
3. we will see the notification message is showing behind the main container

**Expected behavior**
msg should appear in front of main container

**Screenshots**

![Screenshot 2024-05-23 175326](https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/fda5f28f-ea1e-4688-b3ee-2d151a9b72fa)

**Comment by Gamerking177** [comment]
please assign this to me @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 You are already assigned an issue #102

**Comment by SUGAM-ARORA** [comment]
@Gamerking177 Issue assigned to you

**Comment by Ketanop321** [comment]
This issue has been resolved

**Comment by lassmara** [comment]
please assign me this issue

**Comment by sanskriti-lal** [comment]
I want to work on this issue under GSSoC'24. Please assign me this.

**Comment by SUGAM-ARORA** [comment]
@Gamerking177 Are you up for this na?

**Comment by lassmara** [comment]
please assign me this issue

**Comment by SUGAM-ARORA** [comment]
@lassmara Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
This issue is already solved now
