### ISSUE TITLE
[Feat]: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [SUGAM-ARORA/UniCollab#142]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to the problem of lack of communication and acknowledgment when issues are closed in the repository. Contributors may feel neglected or uncertain about the status of their issues if they are closed without any feedback or acknowledgment. This can lead to frustration and a decrease in motivation to contribute further.

**Describe the solution you'd like**
The solution is to automatically post a comment on the issue whenever it gets closed. This comment should thank the issue creator for their contribution and inform them that their issue has been closed. The message can include the issue number and a friendly greeting to make it more personal. This automation ensures that every closed issue receives a consistent and timely response, improving communication and contributor experience.

**Additional context**
![issue closed](https://github.com/SUGAM-ARORA/UniCollab/assets/115717746/08eadd60-4281-4be9-951c-c58d4503a37b)

**Comment by Asymtode712** [comment]
@SUGAM-ARORA please assign me this issue

**Comment by Asymtode712** [comment]
@SUGAM-ARORA i am done with issues 140 & 141 so please assign me this issue

**Comment by SUGAM-ARORA** [comment]
@Asymtode712 Issue assigned to you
