### ISSUE TITLE
Clicking 'Contact' Button Displays Blank Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#144]
**Describe the bug**
When the "Contact" button at the bottom of the page is clicked, it results in a blank page being displayed.

**To Reproduce**
1. Scroll to the bottom of the page.
2. Click on the "Contact" button.
3. Observe that a blank page appears.

**Expected behavior**
Clicking the "Contact" button should display a properly formatted contact page with complete details, including email addresses, phone numbers, and physical addresses.

**Screenshots/Videos**

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/b41f7b6b-e095-4c5d-9b27-092a5d19efe0

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
