### ISSUE TITLE
Enhancements to Image Handling and Timeout Cleanup in MainContainer and CardMain Components

### ISSUE THREAD

**Issue by SamFusedBits** [SUGAM-ARORA/UniCollab#146]
**Is your feature request related to a problem? Please describe.**
The current implementation of the MainContainer and CardMain components has a few areas that could be improved for better code maintainability and user experience. Specifically, the image size limit is hardcoded in MainContainer and the hideTimeout variable in CardMain is not cleaned up when the component unmounts.

**Describe the solution you'd like**
- Refactor the hardcoded image size limit in MainContainer into a constant for better maintainability. This will make it easier to adjust the limit in the future if needed.
- In CardMain, use useEffect to clean up the hideTimeout variable when the component unmounts to prevent potential memory leaks.

**Comment by SUGAM-ARORA** [comment]
@SamFusedBits Issue assigned to you
