### ISSUE TITLE
The left Navbar and right side panel should be fixed

### ISSUE THREAD

**Issue by Utsavladia** [SUGAM-ARORA/UniCollab#149]
**Is your feature request related to a problem? Please describe.**
The navbar should be fixed to improve the user experience of scrolling the middle panel of posts only as we see in websites like instagram

**Describe the solution you'd like**
I would make the navbar and right side panel fixed to the page and improve the UI of middle panel to make it more responsive so that the user will get a better experience of using this app.

**Additional context**

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/124615886/731fe8ae-2dc8-411b-8021-52712526c187)

here we should have more cards and aligned properly in wrap form of using the grid to make it look better.

**Comment by SUGAM-ARORA** [comment]
@Utsavladia Issue assigned to you

**Comment by Utsavladia** [comment]
> @Utsavladia Issue assigned to you

Thank you.. I will try to complete this soon and open a PR.
