### ISSUE TITLE
Adding social media icons in the footer

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [SUGAM-ARORA/UniCollab#150]
**Is your feature request related to a problem? Please describe.**
Adding social media icons in the footer

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SUGAM-ARORA** [comment]
@RamakrushnaBiswal Issue assigned to you

**Comment by Priti9075** [comment]
I'm incredibly enthusiastic about tackling the "Adding social media icons in the footer " issue for GSoC 2024!  Is there a possibility of me being assigned this issue?

**Comment by SUGAM-ARORA** [comment]
@Priti9075 What additional feature you would do in this? Plus @RamakrushnaBiswal has already added social media icons

**Comment by RamakrushnaBiswal** [comment]
Pr #160 issue solved
