### ISSUE TITLE
Adding pointer to cursor while hovering in the cards

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [SUGAM-ARORA/UniCollab#151]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

https://github.com/SUGAM-ARORA/UniCollab/assets/125277258/f0c29bcc-8786-4406-9290-40ebcc51b0a4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SUGAM-ARORA** [comment]
@RamakrushnaBiswal You are already assigned an issue #150

**Comment by RamakrushnaBiswal** [comment]
Hi @SUGAM-ARORA now you can assign it to me 🥹
