### ISSUE TITLE
Implementing a FAQ page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#157]
In the footer section , when we click on 'FAQ' , it shows blank page. I would like to create a FAQ page. I request you to assign this task to me under Gssoc

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/f9882df7-e0c6-4421-88cc-743c4fff1c20)

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora You are already assigned an issue #42

**Comment by Ojas-Arora** [comment]
> @Ojas-Arora You are already assigned an issue #42

@SUGAM-ARORA I have made the required changes and PR will be sent today only. Kindly assign this issue to me!

**Comment by SUGAM-ARORA** [comment]
> > @Ojas-Arora You are already assigned an issue #42
> 
> @SUGAM-ARORA I have made the required changes and PR will be sent today only. Kindly assign this issue to me!

Ok.

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
