### ISSUE TITLE
Making Navbar responsive for all devices

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#169]
**Is your feature request related to a problem? Please describe.**
The problem is that the navbar occupies the whole page followed by main body section. Which is very ugly look and feel. 

**Describe the solution you'd like**
I want to make the navbar responsive so that It will bring modernized and better look and feel. I want to make it responsive for multiple devices like phone, tab, pc etc.

**Describe alternatives you've considered**
I also want to make the footer section responsive. Which improves the website's appearance.

**Additional context**
Screenshot:
![Screenshot 2024-05-27 192306](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/5bdc58cd-c236-4353-bfca-5c862c733902)
![Screenshot 2024-05-27 192326](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/b3d175a1-5105-40c8-bcd2-9f6512e70a59)

![Screenshot 2024-05-27 192343](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/f92b0da4-2a1c-4b40-8686-9d1df1cc2c30)

Please assign me this issue under GSSOC 2024

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged
