### ISSUE TITLE
Implementation of TO DO project 

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#170]
**Is your feature request related to a problem? Please describe.**
I saw the project layout in the website, and I got an idea to implement it. This project will be awesome for the website.

**Describe the solution you'd like**
I want to create a website for TO DO list project implemented using HTML, CSS and JavaScript. And link this project to card in the website.

**Describe alternatives you've considered**
I will make it fully functional and easy to use.

**Comment by saketh-05** [comment]
![todo](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/45282941-57cd-4e69-a430-9241ffcf7749)

Please assign me this issue.

**Comment by SUGAM-ARORA** [comment]
@saketh-05 You are already assigned an issue #169

**Comment by saketh-05** [comment]
@SUGAM-ARORA I have completed my previously assigned issue #169. Please assign me this issue. I want to work on it.

**Comment by saketh-05** [comment]
@SUGAM-ARORA Please assign this to me under Gssoc2024. I have completed my previous issue.

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you

**Comment by saketh-05** [comment]
@SUGAM-ARORA Thank you for assigning this issue.
