### ISSUE TITLE
Alllow users to upload their own projects

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [SUGAM-ARORA/UniCollab#172]
I would like to add a feature that will allow users to upload their projects.

My solution:
- Display an icon for projects in the sidebar.
- By clicking that icon they can navigate to projects page.
- There they can view all the projects, which they have uploaded previously.
- Display a add project button on top of that page.
- By clicking that button users can navigate to add project form with fields title, description, image, developer, github repo link and technologies used.

Kindly please assign this issue to me. I am eagerly waiting to work on this issue.

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Issue assigned to you

**Comment by DharshiBalasubramaniyam** [comment]
@SUGAM-ARORA, thank you for assigning me.
