### ISSUE TITLE
top contributor scroll feature

### ISSUE THREAD

**Issue by Ketanop321** [SUGAM-ARORA/UniCollab#174]
https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/22c50481-1ffc-40c3-9fd2-b96071849839

If you want this feature in top contributor than i will try my best to add this feature this time

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 You are already assigned an issue

**Comment by SUGAM-ARORA** [comment]
#102

**Comment by Ketanop321** [comment]
> @Ketanop321 You are already assigned an issue

That issue #102 has been closed because you said you don't want that feature, so please assign me this one

**Comment by Ketanop321** [comment]
> @Ketanop321 You are already assigned an issue

please assign me this issue ,that issue had been already solved

**Comment by Ketanop321** [comment]
can you assign me this one @SUGAM-ARORA

**Comment by Ketanop321** [comment]
@SUGAM-ARORA  can you look at this issue

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 Issue assigned to you
