### ISSUE TITLE
Dropdown in My profile button is getting on right side

### ISSUE THREAD

**Issue by Ketanop321** [SUGAM-ARORA/UniCollab#175]
Dropdown menu is open on right side of webpage

**To Reproduce**
1. Go to website
2. 2.scroll to right side 

**Expected behavior**
It should to be open when clicking dropdown button

**Screenshots**
![Screenshot 2024-05-28 090305](https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/f6abfaf1-1687-4b0a-bc50-8b98a06e6450)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Device: [Redmi 12]
 - Browser [chrome]

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 This issue already exists
