### ISSUE TITLE
add smooth scroll on back to top button

### ISSUE THREAD

**Issue by Ketanop321** [SUGAM-ARORA/UniCollab#176]
In your webpage when we click on back to top it goes directly up to top , instead it should go with scroll 

I want to add smooth scroll feature when someone click on back to top button, so it goes smoothly at top with scrolling 

I will use property of css like scroll-behaviour:smooth; and many more to fix this

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 You are already assigned an issue #102

**Comment by Ketanop321** [comment]
> @Ketanop321 You are already assigned an issue #102 

But you told me that you don't need that feature

**Comment by Ketanop321** [comment]
> @Ketanop321 You are already assigned an issue #102

that issue is already solve by someone and i have closed that issue

**Comment by Gamerking177** [comment]
pls assign me @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 Issue assigned to you

**Comment by Ketanop321** [comment]
@SUGAM-ARORA can you see my pull request of this issue
