### ISSUE TITLE
Enhance the Footer and make it responsive

### ISSUE THREAD

**Issue by Hemashree21** [SUGAM-ARORA/UniCollab#178]
The Footer is not responsive and also the current design is kind of too clustered. I want to work on redesigning the footer and also making it responsive across all devices.

@SUGAM-ARORA can you please assign this issue to me?

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/138188163/f03426ff-b564-49ee-8ff1-5a934c55c4f1)

![Screenshot 2024-05-16 092104](https://github.com/SUGAM-ARORA/UniCollab/assets/138188163/2936812b-848f-46cc-bdc3-d42859f0962d)

**Comment by rishuraj1708** [comment]
Hey there, I want to work on this issue, will you please assign this to me

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged #223
