### ISSUE TITLE
Implement User Authorization and Sign-in/Sign-up Pages

### ISSUE THREAD

**Issue by Pratik2401** [SUGAM-ARORA/UniCollab#18]
This task involves implementing user authorization functionality to secure access to the website's features. Additionally, sign-in and sign-up pages will be developed to facilitate user authentication and registration. By incorporating user authorization, we ensure that only authenticated users can access specific areas of the website, enhancing security. The creation of sign-in and sign-up pages will streamline the user registration process and improve overall user experience. Assigning this task for GSSoC contribution will lead to the successful implementation of user authentication and a seamless sign-in/sign-up process on the website.

**Comment by Pratik2401** [comment]
Please assign me these

**Comment by nakul2207** [comment]
please assign me these

**Comment by SUGAM-ARORA** [comment]
@Pratik2401 Issue has been assigned to you.

**Comment by VanshGoyal000** [comment]
Hey if issue is not solved till , you can assign it to me! as i am proficient in making these things.

**Comment by Pratik2401** [comment]
I have completed the ui sorry for delay but it will take 2-3 days as my endsem exam is ongoing

**Comment by VanshGoyal000** [comment]
okay then , if you need help in backend you can connect to me.

**Comment by n14rishitha** [comment]
Hi @SUGAM-ARORA 
I will create the Signin page for those who want to signup to the page and make a use of it .I would like to work on this issue . so please assign this task to me under the label gssoc24 and level 1,2,or 3

**Comment by Pratik2401** [comment]
> okay then , if you need help in backend you can connect to me.

Yes ofcourse

**Comment by SUGAM-ARORA** [comment]
> I have completed the ui sorry for delay but it will take 2-3 days as my endsem exam is ongoing

Np @Pratik2401 . Take your time. Generally contributors get min 1-2 weeks of time for issue. So you can focus on endsem and then can come back to this.

**Comment by SUGAM-ARORA** [comment]
This is already completed now
