### ISSUE TITLE
[Bug]: Issue in autocommenting on merged pr

### ISSUE THREAD

**Issue by Anshika14528** [SUGAM-ARORA/UniCollab#184]
**Describe the bug**
I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message

**Screenshots**
<img width="1442" alt="Screenshot 2024-05-29 at 6 50 37 PM" src="https://github.com/SUGAM-ARORA/UniCollab/assets/168436423/9a568b59-3ee0-4b51-9b05-dcbbd7f69f1f">

please let me work on this

**Comment by SUGAM-ARORA** [comment]
@Anshika14528 This issue already exists #182

**Comment by Anshika14528** [comment]
@SUGAM-ARORA sir, #182 is merged now but then also autocomment on pr-merge is not working 
can you please assign me the issue now
