### ISSUE TITLE
Responsiveness of left sidebar in website

### ISSUE THREAD

**Issue by PANDEYS432** [SUGAM-ARORA/UniCollab#188]
The current website page, when checked for responsiveness leaves an odd space next to the left sidebar.  I want to correct it for different views. Please assign the issue to me.
![Screenshot (972)](https://github.com/SUGAM-ARORA/UniCollab/assets/98703881/8728fdbb-4dfb-46c9-b92b-704e9eaafc48)

**Comment by SUGAM-ARORA** [comment]
@PANDEYS432 Issue assigned to you

**Comment by anwesha2002** [comment]
@SUGAM-ARORA seems like author is not working on this anymore u can assign this to me I am a gssoc'24 participants

**Comment by SUGAM-ARORA** [comment]
@anwesha2002 Issue assigned to you
