### ISSUE TITLE
Introducing Premium Features

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#190]
To enrich the website experience, we propose introducing a "Go Pro!" button, offering an array of premium features. Please refer to the attached photo for further details.

![go pro](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/ebf341e7-937b-4d88-883c-7527ad2358d2)

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
