### ISSUE TITLE
Introducing more projects in the feed 

### ISSUE THREAD

**Issue by aasthakourav20** [SUGAM-ARORA/UniCollab#191]
Hey @SUGAM-ARORA , I would like to add 3 more projects in the feed section . 
So that we have more features available to the users .

Please assign this issue to me under GSSoC'24.

**Comment by SUGAM-ARORA** [comment]
@aasthakourav20 Actually we don't need more projects. Actually the aim of this project is to be a platform where students put forward their projects and showcase this to others. These are just sample cards . But for the start it is also necessary to have many projects in this . So you can add these more projects.

**Comment by SUGAM-ARORA** [comment]
@aasthakourav20 Issue assigned to you
