### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [SUGAM-ARORA/UniCollab#2]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by devidutta-learn** [comment]
I am participating in GSSOC'24 and I am interested in this issue, Could you please assign me.

**Comment by SUGAM-ARORA** [comment]
CODE_OF_CONDUCT.md file has been added

**Comment by SUGAM-ARORA** [comment]
Hey @suhanipaliwal  and @devidutta-learn ,

I've added the CODE_OF_CONDUCT as required by the project mentor. If you have any suggestions for changes, please feel free to create an issue, and I'll assign it.
