### ISSUE TITLE
search bar 

### ISSUE THREAD

**Issue by GOURAVSINGH19** [SUGAM-ARORA/UniCollab#201]
**Describe the bug**
In search bar icon is not in their position and its visibility is not good
**To Reproduce**
1. Go to '..Search bar'

**Screenshots**
![Screenshot 2024-06-01 003838](https://github.com/SUGAM-ARORA/UniCollab/assets/120244528/90e37a2b-abcc-42b8-b0b1-d05024d398fd)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SUGAM-ARORA** [comment]
@GOURAVSINGH19 Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged
