### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [SUGAM-ARORA/UniCollab#202]
### Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/73957207/b7ba454d-94f8-4869-83f5-5263fb5f98c2)

- and issue templates:

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/73957207/048543bf-5090-4a75-bbb2-cbf29d6dc5b4)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by SUGAM-ARORA** [comment]
@TonyStark-47 Issue already exists #182

**Comment by TonyStark-47** [comment]
Okay, I will wait 1 day more because he didn't completed his work yet and it's already 4 day passed.

**Comment by SUGAM-ARORA** [comment]
Work already done

**Comment by SUGAM-ARORA** [comment]
@TonyStark-47 Contributors are given 1-2 weeks time to complete each issue.
