### ISSUE TITLE
Enhancing User Engagement with Random Developer Names and Profile Pages

### ISSUE THREAD

**Issue by mohangolakoti** [SUGAM-ARORA/UniCollab#204]
Hello @SUGAM-ARORA,
I have implemented dynamic display of developer names and their information in place of placeholder "Abc".  Additionally, clicking on "View Profile" now navigates to a separate page displaying the respective developer's profile.

The use of random names in place of "Abc" on the web page serves to create a more dynamic and realistic user experience. By incorporating actual developer names, users can better visualize the team behind the project, fostering a sense of authenticity and professionalism. 

Screenshot:
![devs-feat](https://github.com/SUGAM-ARORA/UniCollab/assets/116739999/be7a7461-6fb1-4334-a506-0b4763d68f07)

Please assign me this issue. I have successfully added the feature to dynamically display developer names on the web page and implemented profile pages for each developer.

**Comment by SUGAM-ARORA** [comment]
@mohangolakoti Issue assigned to you

**Comment by kunwarnaunihalsingh** [comment]
hey, please assign this project to me since I believe that my skills in HTML, CSS and JS make me an ideal fit to contribute for your project.

**Comment by mohangolakoti** [comment]
Hey @SUGAM-ARORA , Please check the PR #230
