### ISSUE TITLE
Footer needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [SUGAM-ARORA/UniCollab#211]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20240602_173607](https://github.com/SUGAM-ARORA/UniCollab/assets/59639410/511c9048-5e08-4a58-88d1-b0a7588e50b9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapilG0** [comment]
Hello @SUGAM-ARORA please assign this issue to me under gssoc 24

**Comment by SUGAM-ARORA** [comment]
@kapilG0 This issue already exists #209

**Comment by kapilG0** [comment]
Ok
