### ISSUE TITLE
The View more option in top contributor section and statistics is not working

### ISSUE THREAD

**Issue by Amishachoudhary22** [SUGAM-ARORA/UniCollab#212]
The "View more" option in the top contributor section and the statistics section is not functioning correctly. Clicking the button does not load additional content or navigate to a new page as expected.

To Reproduce

Go to the homepage/dashboard of the application.
Scroll down to the "Top Contributors" section.
Click on the "View more" button.
Scroll further to the "Statistics" section.
Click on the "View more" button.
Observe that nothing happens, and no additional content is loaded.
Expected behavior
Clicking the "View more" button should either load additional content in the current view or navigate to a new page displaying more details about the top contributors or statistics.
<img width="393" alt="Screenshot 2024-06-02 at 10 19 23 PM" src="https://github.com/SUGAM-ARORA/UniCollab/assets/103454929/16f73eb1-af13-48ed-bc19-c6c7b223477c">

**Comment by SUGAM-ARORA** [comment]
@Amishachoudhary22 Issue assigned to you

**Comment by Amishachoudhary22** [comment]
Thank you for assigning this issue to me.
