### ISSUE TITLE
Adding navbar on top 

### ISSUE THREAD

**Issue by Dilpreet0501** [SUGAM-ARORA/UniCollab#213]
**Describe the bug**
 Hello @SUGAM-ARORA , Putting home, about etc all at top of page in navbar section.
Kindly assign me this under GSSoC'24. I'll do my best.

**Screenshot**

![Screenshot 2024-06-02 222733](https://github.com/SUGAM-ARORA/UniCollab/assets/100590445/4de56c44-3eb5-4d3e-85ac-d920a24faad3)

**Comment by KavyaBS123** [comment]
Hey @SUGAM-ARORA can you please assign this issue to me I would be glad to work on it and please label the issue as GSSOC

**Comment by SUGAM-ARORA** [comment]
@Dilpreet0501 Issue assigned to you .
