### ISSUE TITLE
Adding of "Profile" Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#217]
The website is missing a 'Profile' page in the account section, which is necessary. A complete profile page should be created, including an 'About' section and other relevant sections.

![Profile](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/e480a45a-f303-4439-ab81-e75bc1c218f2)

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
