### ISSUE TITLE
There is no login page for this website.

### ISSUE THREAD

**Issue by ayushrskiaa** [SUGAM-ARORA/UniCollab#231]
I can make a login page for this website.

**Comment by ayushrskiaa** [comment]
@SUGAM-ARORA  please assign this issue to me under the GSSoC 24 and add the labels.
Thank you.

**Comment by KavyaBS123** [comment]
Hey @SUGAM-ARORA I am GSSOC contributor can you please label the issue as GSSOC and assign this issue to me I would be glad to work on it!

**Comment by SUGAM-ARORA** [comment]
@ayushrskiaa Issue already exist
