### ISSUE TITLE
Want to add sent mail functionality to the owner in contact us from using email.js

### ISSUE THREAD

**Issue by AnitSarkar123** [SUGAM-ARORA/UniCollab#237]
Assign me under GSSOC 24

**Comment by protyoya** [comment]
can i work on this issue?

**Comment by IAlgorithmia** [comment]
@SUGAM-ARORA Can I work on resolving this issue?

**Comment by SUGAM-ARORA** [comment]
@IAlgorithmia Yes you can work on this issue. But the gssoc has ended so you won't get any points

**Comment by SUGAM-ARORA** [comment]
@IAlgorithmia If you are okay with that then tell me .

**Comment by IAlgorithmia** [comment]
Absolutely @SUGAM-ARORA , I'm here because I loved the project idea

I'm excited to begin working on all the issues, beginning with this one

**Comment by SUGAM-ARORA** [comment]
@IAlgorithmia Issue assigned to you

**Comment by IAlgorithmia** [comment]
Hey there @SUGAM-ARORA 

I have completed the addition of EmailJS in contact us form, also, sending attachments like images, pdfs, etc via email.js requires us to purchase its premium. 

I have attached the example template of sent email via EmailJS. I have used one of my personal emails as the owner email.

Please verify the status and suggest any changes if needed, I will request a PR after your confirmation.

![TemplateEmailJS](https://github.com/user-attachments/assets/1de7c5a6-671c-4bcb-9595-4453d33547ab)

**Comment by IAlgorithmia** [comment]
@SUGAM-ARORA I have made the necessary changes and opened a pull request.

Can you please review it and merge if no issues arise?
