### ISSUE TITLE
Wrong spelling of Services

### ISSUE THREAD

**Issue by kashnx** [SUGAM-ARORA/UniCollab#243]
![Screenshot_2024-06-06-01-43-45-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/SUGAM-ARORA/UniCollab/assets/148524648/8cae9080-47a4-4d44-9cb6-196cbc29e355)
Please assign this issue to me

**Comment by SUGAM-ARORA** [comment]
@kashnx This issue already exists
