### ISSUE TITLE
Footer icons are not working 

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#245]
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/8a35882a-4b56-495b-a586-6ee64d95ec0a)
@SUGAM-ARORA I would like to work on this. Kindly assign me this issue .

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora This issue already exists

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA There are a lot of problems in the footer. It is not possible for anyone to easily solve this.Kindly assign me this I will support this.

**Comment by SUGAM-ARORA** [comment]
Ok @Ojas-Arora
