### ISSUE TITLE
Feature : I want to add a Terms and Conditions Page to be directed from the footer section. I want to contribute under GSSOC' 24. 

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [SUGAM-ARORA/UniCollab#247]
I want to add a Terms and Conditions Page to be directed from the footer section. When the user clicks on the link in the footer, he will be directed to the corresponding page.

**Comment by SUGAM-ARORA** [comment]
@ParnaRoyChowdhury777 This issue already exists
