### ISSUE TITLE
[Bug] : Button Accessability

### ISSUE THREAD

**Issue by sivaprasath2004** [SUGAM-ARORA/UniCollab#25]
- If the right side `Top contributor` containers button are hover not pointing.
- If the button we will hover that cannot be responding. 
![Screenshot from 2024-05-11 18-58-22](https://github.com/SUGAM-ARORA/UniCollab/assets/121082414/b0a1914f-57be-48a0-83f2-e78af3a59bbe)

**Comment by SUGAM-ARORA** [comment]
@sivaprasath2004 Are u up for this?

**Comment by Kalyan9064** [comment]
Hello @SUGAM-ARORA 

I hope this message finds you well. I'd like to express my interest in the task of adding a hover effect to the follow button. With my experience in front-end development and CSS, I'm confident I can implement an engaging and visually appealing hover effect that enhances user interaction. Please consider assigning me this issue, and I'll ensure to deliver a polished solution.

Looking forward to contributing to the project.

Best regards,
Kalyan Chakraborty

**Comment by Riyasharma1311** [comment]
@SUGAM-ARORA Please assign me this . I am highly proficient in such styling and this feature also looks a lot interesting to work on .

**Comment by SUGAM-ARORA** [comment]
Merged
