### ISSUE TITLE
kubernetes for app container

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [SUGAM-ARORA/UniCollab#251]
As the app is dockerize then i think it is also good to apply kubernetes on that container because kubernetes helps as a load balancer when more user base use the app and also help to revive the server automatic when it is down

If you assign me this issue under Gssoc'24 I try to implement this feature

**Comment by SUGAM-ARORA** [comment]
@agarwalhimanshugaya Issue assigned to you

**Comment by agarwalhimanshugaya** [comment]
@SUGAM-ARORA i need to discuss about something related to this issue where can i talk to you?
