### ISSUE TITLE
[BUG] The header is not responsible at all

### ISSUE THREAD

**Issue by vilasini-v** [SUGAM-ARORA/UniCollab#253]
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/115165428/33e41781-eb9d-4cb1-8410-31bcf87667bd)

My solution: 
- Move the search bar below the header to create room for logo, GET PRO button and profile and notifications.
- thus maintaining a clean and function view

**Comment by SUGAM-ARORA** [comment]
@vilasini-v Issue already exists
