### ISSUE TITLE
Add background shadow on about us page

### ISSUE THREAD

**Issue by supriyagaut** [SUGAM-ARORA/UniCollab#261]
@SUGAM-ARORA adding shadow  on the div it more user attractive .
kindly assign me the issue under GSSOC'24. I would like to work on the issue.
![Uploading Screenshot 2024-06-10 174751.png…]()

**Comment by SUGAM-ARORA** [comment]
@supriyagaut Your screenshot is not visible

**Comment by supriyagaut** [comment]
I will send it again

**Comment by SUGAM-ARORA** [comment]
@supriyagaut Issue assigned to you
