### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by SUGAM-ARORA** [SUGAM-ARORA/UniCollab#268]
Previously the page was aligned perfectly .But now it has some alignment issues
Earlier : 
![Screenshot (2)](https://github.com/SUGAM-ARORA/UniCollab/assets/96546088/0ffcacdc-898a-4657-a869-13fc0bda489d)
Now :
![Screenshot (4)](https://github.com/SUGAM-ARORA/UniCollab/assets/96546088/2f9b322b-c7e8-4cce-9d4f-2ba0229488e3)

**Comment by supriyagaut** [comment]
@SUGAM-ARORA kindly assigm me this issue under GSSOC' 24.
I would like to work on this issue.

**Comment by Sneha0019** [comment]
Hey, @SUGAM-ARORA  I can resolve this issue! Please assign me under Gssoc'24 under an appropriate level.

**Comment by mohangolakoti** [comment]
Hey @SUGAM-ARORA, Please assign me this issue I will make those aligned properly.

**Comment by SUGAM-ARORA** [comment]
@Sneha0019 Issue assigned to you

**Comment by Sneha0019** [comment]
Requesting to review and close this issue as I have resolved and made necessary updates in branch as said!
