### ISSUE TITLE
Color coordination issue 

### ISSUE THREAD

**Issue by SUGAM-ARORA** [SUGAM-ARORA/UniCollab#269]
Color code is not in sync witht the whole website . Need to have same color coordination for all. Eg: Login page has different color set , main page differet, contact and other features different

**Comment by supriyagaut** [comment]
@SUGAM-ARORA kindly assign me this issue i would like to work on this issue under GSSOC' 24.
I have earlier work on same issues on zomato clone and prime video clone so kindly assign me this issue.

**Comment by SUGAM-ARORA** [comment]
@supriyagaut Issue assigned to you
