### ISSUE TITLE
Enchancing Login Page and Functionality

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#270]
@SUGAM-ARORA  
https://youtu.be/rWQeqH526KA?si=UOgzMQNaHl7zbi12  I would like to add animation on the Login Page just like done in the above link and will add some more features to the Login Page. Kindly assign this issue to me.

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
