### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by taneeshaa15** [SUGAM-ARORA/UniCollab#272]
Implement client-side form validation to improve user experience and prevent incorrect form submissions.

**Comment by taneeshaa15** [comment]
@SUGAM-ARORA Please assign this issue to me under gssoc'24.

**Comment by SUGAM-ARORA** [comment]
@taneeshaa15 Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged
