### ISSUE TITLE
bug: Create account page is not responsive

### ISSUE THREAD

**Issue by Jagpreet153** [SUGAM-ARORA/UniCollab#280]
![Screenshot 2024-06-11 201642](https://github.com/SUGAM-ARORA/UniCollab/assets/119691733/a66e37f7-38fd-4223-9250-b293f11ddf5c)
![Screenshot 2024-06-11 201702](https://github.com/SUGAM-ARORA/UniCollab/assets/119691733/f72c0501-2ccc-4499-b673-28a7abcefa15)
The create account page is not responsive in mobile as well as laptop screens .Kindly assign this task to me under GSSoC'24

**Comment by SUGAM-ARORA** [comment]
@Jagpreet153 Kindly check the updated one and let me know if it is working or not

**Comment by Jagpreet153** [comment]
It is not responsive for all screens
![Screenshot 2024-06-12 001107](https://github.com/SUGAM-ARORA/UniCollab/assets/119691733/c2227ad4-ddb5-4568-9c04-8434849b8fa8)

**Comment by SUGAM-ARORA** [comment]
@Jagpreet153 Issue assigned to you
