### ISSUE TITLE
Connecting Login Page to the Main Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#285]
I want to connect the Login Page buttons to the main Page of the website that is connecting it ot the Backend. Kindly assign this issue to me @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Not able to work on it.
