### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by Tejashri-Taral** [SUGAM-ARORA/UniCollab#287]
Hey @SUGAM-ARORA ,

I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

****Screenshot (Mandatory):****

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/160386036/20f5c7a7-88a0-4ebf-babc-394a34b14a17)

@SUGAM-ARORA ,Could you please assign me this issue under gssoc'24 ?

Are you contributing under any open-source program ?
GSSOC'24

**Comment by SUGAM-ARORA** [comment]
@Tejashri-Taral Issue assigned to you

**Comment by tkshsbcue** [comment]
i would like to work on this issue

**Comment by SUGAM-ARORA** [comment]
@tkshsbcue Issue assigned to you
