### ISSUE TITLE
Alignment issue 

### ISSUE THREAD

**Issue by sanskriti-lal** [SUGAM-ARORA/UniCollab#294]
<img width="995" alt="Screenshot 2024-06-13 at 1 43 24 PM" src="https://github.com/SUGAM-ARORA/UniCollab/assets/165655543/f9bff3c9-a541-436e-9c19-d2c9b50c65db">

align the mentioned bars properly in the login page. 
I'm a GSSoC'24 contributor, with a strong understanding of web development and I want to work on this. So can you please assign this issue to me @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@sanskriti-lal This issue already exists
