### ISSUE TITLE
Select button missing 

### ISSUE THREAD

**Issue by sanskriti-lal** [SUGAM-ARORA/UniCollab#295]
<img width="1419" alt="Screenshot 2024-06-13 at 1 45 39 PM" src="https://github.com/SUGAM-ARORA/UniCollab/assets/165655543/bca1aa68-bcb2-4885-adff-6c1dee5b828f">

Add a button to select the normal unpaid version of UniCollab . Only option to continue with pro version is present there.
I'm a GSSoC'24 contributor, with a strong understanding of web development and I want to work on this. So can you please assign this issue to me @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@sanskriti-lal This has been done deliberately. Since already the free version is available
