### ISSUE TITLE
"FAQ" Page is Not Link to the Navbar and Footer

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#298]
Hey @SUGAM-ARORA 

I've noticed that in Navbar and footer section there is a link for FAQ but it does not navigate to the dedicated page for it

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/1ca44b57-81b3-4a8a-9996-363e9d681bd7)

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/c208fe9f-93dc-4f49-b85c-a44f2095e891)

I would like to take on this task and add navigation links in footer and navbar for Frequently Asked Questions (FAQ)
Could you please assign this issue to me under GSSOC24? Thank You!!

**Comment by SUGAM-ARORA** [comment]
@MastanSayyad Issue already exists
