### ISSUE TITLE
Re-Create "Licensing" Page to Reflect MIT License

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#299]
Hello @SUGAM-ARORA 

The current licensing page on the website does not reflect the MIT license, despite the repository and website being under the MIT license. To ensure clarity professionalism and legal compliance, the licensing page should be updated to display the **MIT license** accurately.

- **For Example Like This:**

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/91d2f66d-18d0-4e35-b9bc-3c1fa6fe158e)

I would like to work on this project under gssoc 24, could you please assign this issue to me? Thank You!!

**Comment by SUGAM-ARORA** [comment]
@MastanSayyad Issue assigned to you
