### ISSUE TITLE
Adding a Career Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#302]
The website currently lacks a dedicated careers page. After thoroughly reviewing the entire codebase, I could not locate any existing implementation for this feature. Therefore, developing and integrating a careers page into the website is necessary.

**Comment by PrakarshSingh5** [comment]
Please assign this task to me i can complete it

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Career Page is already there . Just someone has unlinked it . Moreover when linking is been done you can have a look and can suggest changes in it if you want.

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA, could you please attach a screenshot of the career page file from the codebase? I have reviewed the entire codebase and was unable to locate the career page file. Additionally, I did not find any issues that were closed after the implementation of the career page.

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 In the codebase contact page is not there

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 You had only previously added the contact page.

**Comment by SUGAM-ARORA** [comment]
Are you up for this??

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA, I have attached a screenshot showing the files of various pages, including "Contact Us." However, I couldn't find the "Careers" page either in the folder or in the codebase that I have reviewed.

![Pages](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/213152c2-ae30-4bd1-98bb-d34c0fc32f8d)

**Comment by SUGAM-ARORA** [comment]
Ya @AkshitGarg24 . You can work on Career Page

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA, we can implement the Career Page in two ways:

- For users looking to build their careers with UniCollab.
- For those interested in hiring a freelancer based on their work displayed in UniCollab. I will attach a screenshot for reference.

![Screenshot 2024-06-17 210253](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/3dd4f749-827b-43de-9de1-bed4f72ab310)

Please confirm which option you would like me to proceed with.

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 What are your views on this? Which one you feel resonated better?

**Comment by SUGAM-ARORA** [comment]
I think at the moment 1st option is more relatable at the moment

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA

I think for now, we can implement the first type on our careers page. Instead of requiring an attached photo in the first type, I'll create a form with general application fields for UniCollab careers. However, we should also create a separate page for the second type, as it will help users discover various opportunities relevant to their experience.

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA
> 
> I think for now, we can implement the first type on our careers page. Instead of requiring an attached photo in the first type, I'll create a form with general application fields for UniCollab careers. However, we should also create a separate page for the second type, as it will help users discover various opportunities relevant to their experience.

Works

**Comment by AkshitGarg24** [comment]
> I think at the moment 1st option is more relatable at the moment. But if you could find a way to have both that would be great. I can assign 2 different issues for that too

Instead of making both options in a single category of "Career" is not a good approach according to me. We should make a seperate option for "Hire a Freelancer" or something lile that, and in that I will implement the second type. 

Please let me know any suggestions from your side.

**Comment by SUGAM-ARORA** [comment]
> > I think at the moment 1st option is more relatable at the moment. But if you could find a way to have both that would be great. I can assign 2 different issues for that too
> 
> Instead of making both options in a single category of "Career" is not a good approach according to me. We should make a seperate option for "Hire a Freelancer" or something lile that, and in that I will implement the second type.
> 
> Please let me know any suggestions from your side.

Yes. I didn't meant to include both in one. Just wanted to make sure that both options are there
