### ISSUE TITLE
Improve blogs page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [SUGAM-ARORA/UniCollab#309]
Issues with current blog page
1. No proper title or header
2. The blog card width is not fixed. Initially it has a width and when clicks on it the width increased, which not looks good.
3. No hover effects.
4. Expand collapse icons missing.

Please assign this issue to me for the improvement of blog page.

https://github.com/SUGAM-ARORA/UniCollab/assets/139672976/3a06d5b3-b5a2-49da-8287-06768b612461

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Issue assigned to you
