### ISSUE TITLE
Add reset password feature while login.

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [SUGAM-ARORA/UniCollab#310]
When users forget their passwords, they need a way to reset them. Implementing a "Forgot Password" feature during login will provide users with a process for resetting their passwords without needing to contact support.

steps:
1. add forgot password link in login page
2. create email verification page, which requests registered email from user to ensure the user account.
3. create verification code verification page, where users can enter the verification code, which sent entered email in above page.
4. create password reset form where users can input a new password. This form should enforce password strength requirements and confirm password entries to prevent errors.

please kindly assign this issue to me.

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Issue assigned to you
