### ISSUE TITLE
BUG: Navigation to Home from About page 

### ISSUE THREAD

**Issue by divyansh-2005** [SUGAM-ARORA/UniCollab#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Navigation to Home from About page is missing 
A small Home icon can be added to easy navigation to home.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 If possible do it for all others too.

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Issue assigned to you
