### ISSUE TITLE
login and create account pages are not responsive

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [SUGAM-ARORA/UniCollab#317]
### Describe the feature

Curre.tly the login and create account pages are not correctly visible in the mobile version. I would like to solve this issue. Kindly please assign this to me.

### Add ScreenShots

![Screenshot 2024-06-16 144102](https://github.com/SUGAM-ARORA/UniCollab/assets/139672976/342ec38a-3e0f-4f79-8fa0-249a6f0044f9)
![Screenshot 2024-06-16 144159](https://github.com/SUGAM-ARORA/UniCollab/assets/139672976/03848d71-908a-482d-8559-3dc2a67b1284)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Login page might be changed . So kindly wait for some itme

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Login Page has been fixed . If you find any issue in it you can raise now
