### ISSUE TITLE
Feat: Add backend

### ISSUE THREAD

**Issue by divyansh-2005** [SUGAM-ARORA/UniCollab#318]
### Describe the feature

I want to start with a basic backed for the project to allow signUp, LogIn, logout.

### Add ScreenShots

I Will add backend files.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by divyansh-2005** [comment]
Assign me this issue. I have Experience in building backend

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Are you up for this?

**Comment by divyansh-2005** [comment]
Yes.

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Issue assigned to you
