### ISSUE TITLE
Card issue 

### ISSUE THREAD

**Issue by pankaj-bind** [SUGAM-ARORA/UniCollab#32]
Size of card is odd. It must be same for all the cards.
Assign me this work under GSSoC'24. I will correct it.
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/73558583/e16b01f6-f9fe-46fb-918b-f52a6302340b)

**Comment by SUGAM-ARORA** [comment]
@pankaj-bind Issue has been assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged
