### ISSUE TITLE
Feat: Add "Hover Effect" to "Footer" Contents and Links

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#321]
### Describe the feature

Hey @SUGAM-ARORA 

The content links in the footer section of the website currently lack a hover effect, which would enhance user experience by providing visual feedback when a user interacts with the links. Adding a hover effect will improve the usability and aesthetics of the website.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/8f7af378-3ce0-4b64-aa03-f5ac7a12b796)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jayanththalla** [comment]
please assign me @pa

**Comment by SUGAM-ARORA** [comment]
@jayanththalla This issue is already been resolved
