### ISSUE TITLE
Feat: New Login/Signup Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#324]
### Describe the feature

@SUGAM-ARORA I want to add a new login/signup page as this is not responsive. Kindly assign this issue to me. 

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/38923f78-d28f-4719-8a22-3e3b383e3a5a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
