### ISSUE TITLE
"Re-Formatting" The "FAQ" Page

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA The current FAQ page needs some formatting, I would like to re-format the FAQ section with a proper headline, margin, size, **Responsiveness,** and coloring to look more eye-catching and engaging...

- **Current FAQ**

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/b7481eca-f645-4454-952f-194cb6d50ff8)

- **After The Changes/ Feature Solution**

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/acfdea33-9284-423f-93f8-53f05903c909)

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/0d95e4d3-58af-45f2-aa8e-436685e9371a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@MastanSayyad It is  not much impressive
