### ISSUE TITLE
BUG: Improve file structure

### ISSUE THREAD

**Issue by divyansh-2005** [SUGAM-ARORA/UniCollab#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In source-code the files and different components are not properly arranged.
An improved file structure enhances organization, ensures easy access and retrieval and streamlines *collaboration*, ultimately boosting overall productivity and efficiency.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Issue assigned to you

**Comment by divyansh-2005** [comment]
its giving lots of errors. I am closing this issue.
