### ISSUE TITLE
Restyle "Vertical Scroll Bar" Matching to the Website Theme

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [SUGAM-ARORA/UniCollab#328]
### Describe the feature

Hey @SUGAM-ARORA 

I have notice in your website the current vertical scrollbar needs styling and formatting
I would like to restyle the vertical scroll bar matching to the website design theme.
Could you please assign me this issue under gssoc24?

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/163530398/4cd69dfd-23b1-4048-a0b5-f93be07db4de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@RadhikaMalpani1702 Issue  assigned to you
