### ISSUE TITLE
Add "Website Description" in Footer "Unicolab"

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [SUGAM-ARORA/UniCollab#329]
### Describe the feature

Hey @SUGAM-ARORA 

I would like to add website description under unicolab title as the space is empty
Could you please assign this issue to me under GSSOC24 ?

### Add ScreenShots

 - **Current Footer**

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/163530398/c55bd4e0-36db-493a-9202-3e9581df23b0)

- **Updated Footer**

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/163530398/e7f6923f-1ca3-4468-a354-4962c96543c2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@RadhikaMalpani1702 Issue assigned to you
