### ISSUE TITLE
Feat: Form Notification on clicking a submit button

### ISSUE THREAD

**Issue by DevGajjar28** [SUGAM-ARORA/UniCollab#332]
### Describe the feature

Here my proposal  In Contact us page form , when user field the form and submit that it show a notification that Your form is submitted.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/145287513/87127df6-9b0e-4955-902a-c7e116c464c9)
 As shown in image i would i like to add notification.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@DevGajjar28 Issue  assigned  to you
