### ISSUE TITLE
BUG:header

### ISSUE THREAD

**Issue by aashkaaaaaa** [SUGAM-ARORA/UniCollab#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/138461600/613e2bfe-ed6b-45d8-b31b-37144fd7947b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@aashkaaaaaa This issue is already there
