### ISSUE TITLE
Feat:make the file structure of backend more good 

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [SUGAM-ARORA/UniCollab#335]
### Describe the feature

in backend router and controller put in same place in prouduction level code router is for initialize all the router and in controller we write all the logic i want to make it better

### Add ScreenShots

No screenshot

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@agarwalhimanshugaya Issue assigned to you
