### ISSUE TITLE
Feat: link login and sign up functionality to frontend

### ISSUE THREAD

**Issue by divyansh-2005** [SUGAM-ARORA/UniCollab#338]
### Describe the feature

the backend contains logic of login and sign up. We should link them to allow users to actually login.

### Add ScreenShots

NA.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Issue assigned to you
