### ISSUE TITLE
Add "Back To Home Button" on "Legal Pages"

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#343]
### Describe the feature

Hey @SUGAM-ARORA 

There is a **"Back to Home"** button present on all pages of the website except for the legal pages. 
The legal pages, including **Privacy Policy, Terms and Conditions, and Licensing**, lack this button, in which users might find it inconvenient to navigate back to the homepage.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/00da46d5-a2d6-42e2-b2de-634cff1809e8)

I would like to Add a "Back to Home" button on the following legal pages to improve navigation and user experience:

- Privacy Policy
- Terms and Conditions
- Licensing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@MastanSayyad Issue assigned to you
