### ISSUE TITLE
Feat: Adding Social Media icons to Login Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#345]
### Describe the feature

@SUGAM-ARORA  want to add social media icons as well as images to the Login/Signup Page. Kindly assign this issue to me.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/5db9e41f-2e23-4cfa-8a9d-e2f2505a0aa0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
