### ISSUE TITLE
Feat: Improve features on search results

### ISSUE THREAD

**Issue by SrinivasDevolper** [SUGAM-ARORA/UniCollab#346]
### Describe the feature

1. Add the Wrong icon Button near search for search experience 
2. Add Hover background color 
3. Add cursor pointer 
4. Redesign the scrollbar style to match this website in search results

### Add ScreenShots

1. <img width="721" alt="wrong butotn" src="https://github.com/SUGAM-ARORA/UniCollab/assets/121508628/d8feba54-9a98-40a3-9ff4-e4148c23af2a">

2. https://github.com/SUGAM-ARORA/UniCollab/assets/121508628/5d57f89e-10a5-46cd-a24b-c8696f2052b4

3. ![cursor pinter](https://github.com/SUGAM-ARORA/UniCollab/assets/121508628/7f068a1c-13b1-4076-8f42-95d6a4be6734)

4. https://github.com/SUGAM-ARORA/UniCollab/assets/121508628/5d57f89e-10a5-46cd-a24b-c8696f2052b4

**I am GSSOC24 Contributor
Please assign me,I would like to work on it**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@SrinivasDevolper Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Go Ahead

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Yes
