### ISSUE TITLE
Feat: Enhancement in the Contact page .

### ISSUE THREAD

**Issue by agrwal697** [SUGAM-ARORA/UniCollab#347]
### Describe the feature

I think if the Contact section had border-bottom , placeholder in every text item so it would have better UI and also it is not aligned properly. I would also like to make it responsive.
Please Assign me this issue with the level and label of GSSOC'24

### Add ScreenShots

Before:
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/128716726/ed9033be-8f89-400b-b925-601abd90ac95)

After:
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/128716726/dd4fdae2-1996-42e4-8e5a-3e41bf7d0f52)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@agrwal697 Issue assigned to you
