### ISSUE TITLE
Feat: Adding a "Hire a FreeLancer" web-page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#348]
### Describe the feature

As we have already discussed in issue #302, a dedicated web page for hiring a freelancer based on his experience should be made so that the user will get various opportunities based on what work he has already done.

### Add ScreenShots

![Screenshot 2024-06-17 210253](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/787e3ba7-a74b-4902-b8e1-290323b8a079)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AkshitGarg24** [comment]
For implementing this page, we have two potential approaches:

**1. User's Perspective:**
In this approach, the page will be designed for users seeking opportunities. Users can search for various job openings and apply for those that match their experience and skills.

**2. Hiring Person's Perspective:**
In this approach, the page will be designed for hiring managers looking to find and contact potential candidates based on their work and skills. This is illustrated in the photo attached above.

Could you please advise on which approach to take for implementing this page?

**Recommendation:**
I recommend implementing the page from the Hiring Person's Perspective. This approach aligns with the project's main objective and also provides users with valuable opportunities, adding a rewarding dimension for them. Conversely, implementing it from the User's Perspective would essentially turn it into a job portal, which is not the intended purpose of this project.

I am ready to proceed with any type based on your decision.

Thank you!

**Comment by SUGAM-ARORA** [comment]
> For implementing this page, we have two potential approaches:
> 
> **1. User's Perspective:** In this approach, the page will be designed for users seeking opportunities. Users can search for various job openings and apply for those that match their experience and skills.
> 
> **2. Hiring Person's Perspective:** In this approach, the page will be designed for hiring managers looking to find and contact potential candidates based on their work and skills. This is illustrated in the photo attached above.
> 
> Could you please advise on which approach to take for implementing this page?
> 
> **Recommendation:** I recommend implementing the page from the Hiring Person's Perspective. This approach aligns with the project's main objective and also provides users with valuable opportunities, adding a rewarding dimension for them. Conversely, implementing it from the User's Perspective would essentially turn it into a job portal, which is not the intended purpose of this project.
> 
> I am ready to proceed with any type based on your decision.
> 
> Thank you!

Agreed. Go with hiring person's Perspective
