### ISSUE TITLE
DOC: static documentation site

### ISSUE THREAD

**Issue by Abhishek-Sood** [SUGAM-ARORA/UniCollab#359]
### What's wrong with the existing documentation

there is no documentation ..i d like to propose a static documentation site made using mkdocs 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Abhishek-Sood Issue assigned to you
