### ISSUE TITLE
Feat: Custom Cursor

### ISSUE THREAD

**Issue by chaanakyaaM** [SUGAM-ARORA/UniCollab#361]
### Describe the feature

The website is awesome, but it can look more attractive and professional if there is an custom interactive cursor.

I would like to add custom cursor with trail effect.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@chaanakyaaM Can you share more details about this?

**Comment by chaanakyaaM** [comment]
https://github.com/SUGAM-ARORA/UniCollab/assets/131477601/794043c0-aac6-481f-889b-8eae86459dfd

Like this kind, i can change the color according to the website colors.

**Comment by SUGAM-ARORA** [comment]
> would you assign this to me?

@chaanakyaaM Cursor has already been added. Also enhancement in cursor issue is already there
