### ISSUE TITLE
Feat: Adding Multilingual Facility

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#364]
### Describe the feature

@SUGAM-ARORA I want to add multilingual feature to the website. Kindly assign this issue to me.

### Add ScreenShots

![Screenshot 2024-06-22 174346](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/a77744a5-c164-4cf6-8a04-f1802a37b3c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
