### ISSUE TITLE
BUG 🐞: "Glitchy Cursor" Trail Effect and "Asynchronize Cursor Movement"

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

The current implementation of the cursor trail effect on the website is experiencing significant issues. 
- The cursor and the trail effect are not synchronized, 
- leading to the cursor moving to one location while the trail effect shows up somewhere else. 
- Buttons and links are unable to click
- This results in a glitchy and irritating user experience. 

https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/23fa3e94-13e6-42d5-bc28-0257c087ec8d

This issue impacts the overall user experience negatively and needs to be addressed as a priority.

The goal of this issue is to **fix this synchronization problem** and **ensure the cursor movement is smooth** with an appropriate trail effect.

## Solution

- Review and update the JavaScript code responsible for the cursor trail effect.
- Ensure the event listeners for mouse movements are correctly implemented and optimized.
- Test the synchronization of the cursor and the trail effect across different browsers and devices.
- Implement any necessary performance improvements to make the cursor movement and trail effect smooth.

Please assign me this issue!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@MastanSayyad Issue assigned to you
