### ISSUE TITLE
Fix Footer for Tablet screen 768 px

### ISSUE THREAD

**Issue by Utsavladia** [SUGAM-ARORA/UniCollab#372]
### Describe the feature

Footer should have uniform desing on all screen sizes so should be fixed for the tablet screen also 

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/124615886/6278a5fd-5103-477c-86bd-0550ec96d714)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Utsavladia Issue assigned to you
