### ISSUE TITLE
Adding background border and shadow on the service page also adding the heading of services.

### ISSUE THREAD

**Issue by supriyagaut** [SUGAM-ARORA/UniCollab#373]
![Screenshot 2024-06-23 130947](https://github.com/SUGAM-ARORA/UniCollab/assets/141560711/ea63a9e4-b838-497f-8ee9-ec1a086f0451)

@SUGAM-ARORA  I want to add a background border and background shadow and also add a services heading to enhance the website.
kindly assign me this issue under GSSOC'24. I would like to work on this.

**Comment by SUGAM-ARORA** [comment]
@supriyagaut Issue assigned to you
