### ISSUE TITLE
Recreating careers page

### ISSUE THREAD

**Issue by supriyagaut** [SUGAM-ARORA/UniCollab#374]
![Screenshot 2024-06-23 140135](https://github.com/SUGAM-ARORA/UniCollab/assets/141560711/a6c289a0-952f-4fed-9a24-0808e3d1e5a5)
![Screenshot 2024-06-23 140630](https://github.com/SUGAM-ARORA/UniCollab/assets/141560711/78cf4430-0981-4000-82ba-784bd7a61ae1)

@SUGAM-ARORA I want to change the font size, add proper space, background shadow, and color, and remove underlining on certain words.
it enhances the website kindly assign me this issue I would like to work on this under GSSOC'24.

**Comment by SUGAM-ARORA** [comment]
@supriyagaut Issue assigned to you

**Comment by tkshsbcue** [comment]
i would like to work on this @SUGAM-ARORA
