### ISSUE TITLE
BUG: Login Page is not Responsive 

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Login page is not able to work in mobiles or Tabs. I want to make the login page responsive for all devices which will add new look and feel for the website.
![Screenshot 2024-06-24 085352](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/5f1beaaf-de9b-42ac-a04e-c9f02c947695)
![Screenshot 2024-06-24 085404](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/132c993f-d68a-4323-81b6-d0505032cff1)
![Screenshot 2024-06-24 085419](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/cad30682-16db-4850-8f0c-dbb45f6ff6b3)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saketh-05** [comment]
@SUGAM-ARORA Please assign me this issue, I want to work on it.

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you
