### ISSUE TITLE
Feat:header content flowing outside the card in mobile 

### ISSUE THREAD

**Issue by kapilG0** [SUGAM-ARORA/UniCollab#385]
### Describe the feature

Feat:header content flowing outside the card in mobile

### Add ScreenShots

![Screenshot_20240625_230920](https://github.com/SUGAM-ARORA/UniCollab/assets/59639410/7522f1c3-e849-411a-9747-844c64290090)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @SUGAM-ARORA please assign this issue to me under gssoc 24

**Comment by SUGAM-ARORA** [comment]
@kapilG0 Issue assigned to you

**Comment by anwesha2002** [comment]
@SUGAM-ARORA It's been a month I think author is not working on it anymore can i work on this I am gssoc'24 participants
