### ISSUE TITLE
Feat: Adding Discord , mail and Instagram accounts icon at footer section

### ISSUE THREAD

**Issue by GAVINESHWAR** [SUGAM-ARORA/UniCollab#390]
### Describe the feature

In the footer section of the main page, there are currently only four social media icons. I would like to add icons for Instagram, email, and Discord accounts to further increase the platform's reach.

@SUGAM-ARORA , assign me this issue to make contribution to the project.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/124431955/eb172671-a2e6-4919-9961-6e75a8601de8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@GAVINESHWAR This issue is not required . No particular link for these social media icons is there .Maybe in future we can do this .
