### ISSUE TITLE
BUG: Icon Link

### ISSUE THREAD

**Issue by udayand4s** [SUGAM-ARORA/UniCollab#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Pressing on UC icon wont redirect to the home page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@udayand4s Issue assigned to you
