### ISSUE TITLE
BUG: Add email pattern verification in contact us page.

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The email input in contact us page takes all kinds of emails as input which can lead to data breach sql infections or other issues.
I want to add email pattern verification and improve security of the contact us form. 

![Screenshot 2024-06-27 181024](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/d5ad125f-3334-4138-9c2f-c45b71ad730a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saketh-05** [comment]
@SUGAM-ARORA Please assign this issue to me, I want to work on it.

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you
