### ISSUE TITLE
Feat: Navbar should close

### ISSUE THREAD

**Issue by SrinivasDevolper** [SUGAM-ARORA/UniCollab#399]
### Describe the feature

The navbar should close when the user clicks the Nav item

### Add ScreenShots

https://github.com/SUGAM-ARORA/UniCollab/assets/121508628/27f5cbc8-7f64-4f50-b388-175a73b78f08

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@SrinivasDevolper Issue assigned to you

**Comment by amandeeep02** [comment]
@SUGAM-ARORA Please assign this issue to me.

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Please assign this issue to me.

@amandeeep02 Need to wait as this is already assigned
