### ISSUE TITLE
Feat: Proposing a new FAQ & Services section

### ISSUE THREAD

**Issue by DevGajjar28** [SUGAM-ARORA/UniCollab#401]
### Describe the feature

Currently FAQ & Service page is good but not a professional that enhance user experience .
why: 
first: There is no fixed width.
second Because when click on question it show down the answer on a width hover 

### Add ScreenShots

**Current:**
https://github.com/SUGAM-ARORA/UniCollab/assets/145287513/ab9585cf-c6c1-4989-9d1b-03ea4e1adb0f

**proposed**
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/145287513/06db9551-c875-4381-bbe5-4931d41ddc9d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@DevGajjar28 FAQ page is good for now. we can have a look at it later
