### ISSUE TITLE
BUG: Making Careers Page Responsive

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Careers Page is currently not responsive to all devices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
