### ISSUE TITLE
Feat: Adding subscribe newsletter section

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [SUGAM-ARORA/UniCollab#406]
### Describe the feature

Adding subscribe newsletter section

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/125277258/52760735-ae74-4f6f-9b4f-4c854a73d990)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@RamakrushnaBiswal Issue assigned to you

**Comment by Bliss011** [comment]
@RamakrushnaBiswal  Can you please assign this task to me

**Comment by SUGAM-ARORA** [comment]
@Bliss011 Issue assigned to you
