### ISSUE TITLE
BUG in "Hire A Freelancer" Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The "Hire a Freelancer" page on the main website is displaying incorrectly with larger fonts and sizes. I have cloned the project again, and it displays perfectly on my local system.

- **On Main Website**

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/9c74733e-3136-4cd4-b4fc-fb4b517f15b7

- **On Local Website**

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/f1961862-3af3-47ab-bd3d-22a18ba77566

I am unsure what mistake I might have made. Could you please guide me on this issue? I understand I have already been assigned two other issues, but since I created this page, I want to ensure it is free of bugs.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA , I am thinking to make this page responsive too in this issue only.

**Comment by tkshsbcue** [comment]
@SUGAM-ARORA please assign me this issue
