### ISSUE TITLE
Feat:  Update react-router-dom to version 6 and refactor routing logic

### ISSUE THREAD

**Issue by MinavKaria** [SUGAM-ARORA/UniCollab#410]
### Describe the feature

**Is your feature request related to a problem? Please describe.**
The current routing setup is cumbersome and difficult to manage due to the older version of React Router DOM.

**Describe the solution you'd like**
Update React Router DOM to v6, using createBrowserRouter and RouterProvider for a more efficient routing setup. This will simplify nested routes and improve code maintainability.

**Describe alternatives you've considered**
- Continuing with the older version, which is not sustainable due to deprecated features.
- Using a different routing library, requiring a significant rewrite.

_GSSOC'2024 Contribuitor_

@SUGAM-ARORA Please assign it to me

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/119132631/ea364365-6df5-4019-85bb-c7df115fec33)

to new version like this

```
{
          path: '/route/:id',
          element: <ElementNeeded/>
 },
```

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Please acknowledge

**Comment by SUGAM-ARORA** [comment]
@MinavKaria Issue assigned to you

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Please Acknowledge
