### ISSUE TITLE
BUG: Top Contributor Component Hiding Under Footer in Mobile version 

### ISSUE THREAD

**Issue by MinavKaria** [SUGAM-ARORA/UniCollab#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Top Contributor is box which at the bottom of the mobile version is partially hidden by the footer, that must be fixed.

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/119132631/31f737b9-d6b9-4c36-84e8-8f7d000efdcc)

@SUGAM-ARORA Assign this to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@MinavKaria Issue assigned to you
