### ISSUE TITLE
Feat: Add Google Login using Firebase

### ISSUE THREAD

**Issue by MinavKaria** [SUGAM-ARORA/UniCollab#414]
### Describe the feature

Add google login to the login page for better user experience and faster login. This is a basic feature that must be added to the signup and login page. 

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/119132631/8520f2dc-8182-4112-b44f-bf97cfbe42d7)

@SUGAM-ARORA Please assign this to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@MinavKaria Google login option is already there. Just someone has made mess in alignment

**Comment by SUGAM-ARORA** [comment]
@MinavKaria Just wanted to know what all you wanted to do in this??

**Comment by MinavKaria** [comment]
@SUGAM-ARORA 
Ok If Google login already there that's great, I will fix it and make it visible then and fix the mess created

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Ok If Google login already there that's great, I will fix it and make it visible then and fix the mess created

@MinavKaria Actually this issue exists. If you want you can connect google login using firebase

**Comment by MinavKaria** [comment]
Ok I will , but then will have to add env file where the contributor must add their firebase api keys to use while cloning it , is that ok ?

**Comment by SUGAM-ARORA** [comment]
> Ok I will , but then will have to add env file where the contributor must add their firebase api keys to use while cloning it , is that ok ?

yes

**Comment by MinavKaria** [comment]
In vercel you just add the firebase as environment variable, is that ok then ?

**Comment by SUGAM-ARORA** [comment]
@MinavKaria Issue assigned to you

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Have sent the PR, Pls check
