### ISSUE TITLE
Feat: Centre aligned the To The Top Button

### ISSUE THREAD

**Issue by amandeeep02** [SUGAM-ARORA/UniCollab#415]
### Describe the feature

Have aligned the "To the top" button to center. Works fine in both PC and Mobile view and gives a clean look to the UI.

### Add ScreenShots
Current Website:
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/145058235/7f3bc48f-b97e-4790-8f56-5b91f923be88)
After Update:
![featurepc](https://github.com/SUGAM-ARORA/UniCollab/assets/145058235/10306baf-2c96-43e9-9386-56e36bd455ec)
![featuremobile](https://github.com/SUGAM-ARORA/UniCollab/assets/145058235/bce06dc5-f047-47fb-a15b-aa28cdc7ffa2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by amandeeep02** [comment]
Hello @SUGAM-ARORA  please assign this issue to me under gssoc 24.

**Comment by SUGAM-ARORA** [comment]
@amandeeep02 Issue assigned to you
