### ISSUE TITLE
Feat:Alignment issue

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#417]
### Describe the feature

@SUGAM-ARORA There is a lot of issue in the alignment of the page. Kindly assign this issue to me.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/01871dcb-ba97-407c-a476-99baf70131f6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
