### ISSUE TITLE
BUG: Notifications not visible

### ISSUE THREAD

**Issue by sakshiglaze** [SUGAM-ARORA/UniCollab#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hello @SUGAM-ARORA 
Notifications are not properly visible!

https://github.com/SUGAM-ARORA/UniCollab/assets/129287425/f21e8cfb-8466-480f-aaa3-846774542ec8

 Please assign this under GSSOC and the difficulty label as well!
 Thankyou!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@sakshiglaze This alignment issue is already been taken
