### ISSUE TITLE
Feat: Elevating User Experience: Footer Refinement, Freelancer Page Fixes, and FAQ Styling

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#421]
### Describe the feature

@SUGAM-ARORA There is a problem in footer,hire  a freelancer page and FAQ styling. Kindly assign this issue to me.

### Add ScreenShots
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/5706f745-1d5e-47bd-8e0e-79ea4f16b96f)

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/ebc19529-a174-411f-bd44-8abb1a7c737b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
