### ISSUE TITLE
BUG: The notification dropdown is not visible

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- The drop-down given to notification icon is not aligned properly and so it is not visible. I want to fix the issue with alignment 
- Also modify the content in the drop-down as it contains content which is not much required. I will add content related to the recent changes/updates done to the website including projects.

![Screenshot 2024-07-02 135643](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/215304bd-3bc1-4128-874a-d4bbecbab3a3)
![Screenshot 2024-07-02 135702](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/59991712-390d-468c-b86a-a1bd7a7baf17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 This alignment issue already exists
