### ISSUE TITLE
Feat: Remodeling Hire a Freelancer page

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#424]
### Describe the feature

- Firstly I want to work on **Hire a Freelancer** page because present page has many issues that must be fixed.
### Features I want to add:-

- Add home button
- Make page responsive for all devices
- Properly align cards and change theme of the page according to home page.
- Finally proper integration of all divisions including footer and navbar.

### Add ScreenShots

![Screenshot 2024-07-02 160102](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/b95c3497-1e75-470f-a982-b42c4dec6359)
![Screenshot 2024-07-02 160119](https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/08cf0f28-9116-4173-a411-fad1ccd6babc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 This issue is already there
