### ISSUE TITLE
Feat: UI Refinements: Adding Shadows and Aligning Login Page Elements

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#437]
### Describe the feature

@SUGAM-ARORA I want to add shadow on the Blogs page just like done in About us page and refining the Login Page. Kindly assign this issue to me.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/8cc44631-04ae-4d93-9a50-8e549711b1c1)

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/630020c5-cc23-4bb2-b731-3fd192b1517e)

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/08930552-2321-4462-9576-e80959eead8c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
