### ISSUE TITLE
Feat: Enhancement in the statistics page.

### ISSUE THREAD

**Issue by agrwal697** [SUGAM-ARORA/UniCollab#439]
### Describe the feature

I think if the statistics section had border-bottom , placeholder in every text item so it would have better UI and also it is not aligned properly. I would also like to make it responsive.
Please Assign me this issue with the level and label of GSSOC'24.

### Add ScreenShots

before:
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/128716726/d2d1cc83-ffd7-4622-ad56-ea70454a0a0f)

after:
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/128716726/cf050150-7dbd-4167-856b-9d662676dd38)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@agrwal697 Issue assigned to you
