### ISSUE TITLE
Add Icons To Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [SUGAM-ARORA/UniCollab#441]
### Describe the feature

Hello Project Admin
I would like to add icons to Footer to make website look attractive 

### Add ScreenShots

![IMG_20240706_123501](https://github.com/SUGAM-ARORA/UniCollab/assets/161804629/4c09a5ae-26e6-4705-a458-1899bd472187)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@sailaja-adapa What all icons you want to add??

**Comment by sailaja-adapa** [comment]
![IMG_20240706_233118](https://github.com/SUGAM-ARORA/UniCollab/assets/161804629/5d9c5b7c-080b-4276-8325-e5a64f70ed84)
 I would like to add icons like this

**Comment by SUGAM-ARORA** [comment]
@sailaja-adapa Issue assigned to you

**Comment by sailaja-adapa** [comment]
Ok Thanks @SUGAM-ARORA
