### ISSUE TITLE
Feat: Chatbot Icon

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#443]
### Describe the feature

@SUGAM-ARORA I want to add a chatbot to the website. Kindly assign this issue to me. 

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/2d115c79-be1a-4924-a9ea-83c28ed2d4b1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
