### ISSUE TITLE
BUG: Improve Scroll-to-Top Button 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [SUGAM-ARORA/UniCollab#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

I noticed that the current "To the Top" button in the footer is causing extra space and is positioned at the bottom of the footer. For better accessibility and user experience, I propose moving the scroll-to-top button to the bottom right corner of the screen also I will make the button position fixed screen while scrolling and the button will only appear when the user scrolls down a little.

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/163530398/1d48d088-04ee-4fe2-9914-530f69a33def)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@RadhikaMalpani1702 Issue assigned to you
