### ISSUE TITLE
Feat: Redesign services page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [SUGAM-ARORA/UniCollab#445]
### Describe the feature

The current services page is lack of images and user experience. I would like to design the services page as below. 

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/139672976/bd7fa3c2-7a83-4535-b5e8-8a1d069594d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam You can add more images but don't redesign it much

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Issue assigned to you
