### ISSUE TITLE
Feat: Discover Answers: A Blog-Style FAQ

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#449]
### Describe the feature

@SUGAM-ARORA I want to make the FAQ page similar to that of blog page. Kindly assign this issue to me.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/b7473984-816c-4914-83bc-bd9cf0b6ca38)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
