### ISSUE TITLE
Feat: Add Testimonials Page containing carousel component . I want o contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [SUGAM-ARORA/UniCollab#453]
### Describe the feature

I want to add the Testimonial page for the link present in the footer section.

### Add ScreenShots

![Screenshot 2024-07-07 005236](https://github.com/SUGAM-ARORA/UniCollab/assets/123104247/180e4d68-ada9-4380-a4b3-4ed888c36031)

The link to this testimonial page is not there. so i wish to add the testimonial page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@ParnaRoyChowdhury777 Issue assigned to you

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Can I work on this issue?

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Can I work on this issue?

Yes you can

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
