### ISSUE TITLE
Feat:Transform Your Services Page: Make It as Engaging as Your Blog

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#456]
### Describe the feature

@SUGAM-ARORA I want to make the services page like the blog page. Kindly assign this issue to me.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/b7473984-816c-4914-83bc-bd9cf0b6ca38)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
