### ISSUE TITLE
Add Icons to Navbar

### ISSUE THREAD

**Issue by sailaja-adapa** [SUGAM-ARORA/UniCollab#462]
### Describe the feature

Hello Project Admin
I would like to add Icons to Navbar so that it will make our website to look attractive 
Can you assign me this issue under GSSOC'24 @SUGAM-ARORA 
As you can see in below video

### Add ScreenShots

https://github.com/SUGAM-ARORA/UniCollab/assets/161804629/6cca3419-637f-45cf-89b0-f8cacc2470ba

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@sailaja-adapa Issue assigned to you

**Comment by sailaja-adapa** [comment]
Yeah Thank you @SUGAM-ARORA
