### ISSUE TITLE
Make Topcontributor static

### ISSUE THREAD

**Issue by Ketanop321** [SUGAM-ARORA/UniCollab#465]
### Describe the feature

when we scroll the top contributor list header also gets scroll its should be static 

### Add ScreenShots

https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/c154ade6-3d34-473e-90ba-515a6862fb6d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MinavKaria** [comment]
@SUGAM-ARORA assign this to me

**Comment by Ketanop321** [comment]
@SUGAM-ARORA  can you see this issue??

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 Issue assigned to you
