### ISSUE TITLE
Giving Proper space to the cards

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The cards on the main page contain extra space at the bottom. So the contents of the card should have equal space between them to look good.

![Cards](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/363bd2e7-1bb0-4959-8297-6164563da068)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Please assign this to me, I can do this

**Comment by SUGAM-ARORA** [comment]
@MinavKaria Issue assigned to you

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA I guess I have opened this issue, so it should be assigned to me. I have already made PR for the previous issue so that's also not an issue I guess.

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
