### ISSUE TITLE
Adding hover effects on cards in "Freelancer" page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The cards on the freelancer page lack the hover effect.

![Cards](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/61eb9da3-def3-4b82-90fc-b990c6092b13)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
