### ISSUE TITLE
🌟 Feature: Add a Scroll "Progress Indicator Bar"

### ISSUE THREAD

**Issue by Tejashri-Taral** [SUGAM-ARORA/UniCollab#471]
### Describe the feature

Hey @SUGAM-ARORA ,
I want to add a "Scroll Down Progress Bar"

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page.
The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/160386036/cc917ee4-0420-45e2-bb70-e9a369b3d5de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Tejashri-Taral Issue assigned to you
