### ISSUE TITLE
BUG: Content getting hidden

### ISSUE THREAD

**Issue by komal-agarwal5** [SUGAM-ARORA/UniCollab#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In freelancers page the cards are getting covered by footer,details aren't visible.

![Screenshot 2024-07-10 010028](https://github.com/SUGAM-ARORA/UniCollab/assets/122633300/926dac4e-d66a-40ea-b14e-24f23c31b92e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@komal-agarwal5 Issue assigned to you
