### ISSUE TITLE
Feat: Making a Cart Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#475]
### Describe the feature

@SUGAM-ARORA I want to make the Cart Page for the Website. Kindly assign this issue to me.

### Add ScreenShots

![image](https://github.com/SUGAM-ARORA/UniCollab/assets/127867874/51632a5e-26c3-449f-ad75-b827359b002c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
