### ISSUE TITLE
BUG: Main Page is not responsive for smaller width 

### ISSUE THREAD

**Issue by upsaurav12** [SUGAM-ARORA/UniCollab#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In the main page the nav bar and side container's like ``stats`` and ``top contributor`` are overflowing for smaller width they can be fixed by using display:flex widht adding a media query on ``925px`` 
Here is the video

https://github.com/SUGAM-ARORA/UniCollab/assets/116784047/30828206-917c-49a9-b684-b1ccaea993fc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by upsaurav12** [comment]
I want to work on this issue pls assign me this issue thank you

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Issue assigned to you

**Comment by upsaurav12** [comment]
I am getting merge conflicts whenever i am making a new PR

**Comment by SUGAM-ARORA** [comment]
> I am getting merge conflicts whenever i am making a new PR

Because your branch is not updated. What all issue you are getting while updating branch?? Can you please share
