### ISSUE TITLE
BUG: Hover effect is not working properly 

### ISSUE THREAD

**Issue by upsaurav12** [SUGAM-ARORA/UniCollab#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the hover effect in footer of contact page  ``section-title`` doesnt have proper hover effect like links inside links container 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by upsaurav12** [comment]
i want to work on this project

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Issue assigned to you

**Comment by upsaurav12** [comment]
@SUGAM-ARORA I was working in this issue but having problem while doing setup in docker can you tell me how to do it i am not able to find it

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA I was working in this issue but having problem while doing setup in docker can you tell me how to do it i am not able to find it

Can you share the details about the issue which you faced while doing setup in docker. 
Btw we can do setup without docker too

**Comment by upsaurav12** [comment]
i am not able to understand how to setup in docker there is not documents there

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Setup in docker is not required. Do the setup locally

**Comment by upsaurav12** [comment]
ok understood but i am facing problem that when i am making any changes it does not rendering my changes even in logs
![image](https://github.com/user-attachments/assets/ede19387-0cc5-4071-b6b8-6cd49ddebe03)

**Comment by upsaurav12** [comment]
@SUGAM-ARORA one problem is faced is that to see any changes i had to run ``npm run build`` and later ``serve -s build`` repeatedly so is there any way so that i can do it once?

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA one problem is faced is that to see any changes i had to run `npm run build` and later `serve -s build` repeatedly so is there any way so that i can do it once?

You can check now

**Comment by upsaurav12** [comment]
ok will try again BTW thanks for help
