### ISSUE TITLE
BUG: There are no social media icons in the footer 

### ISSUE THREAD

**Issue by JagjeetChauhan** [SUGAM-ARORA/UniCollab#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

When I was scrolling the site I found that the footer does not have social media icons nor any links
![image](https://github.com/user-attachments/assets/9b5a6e0f-250c-4dc4-809d-8aa0664a8bc4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@JagjeetChauhan This issue exists
