### ISSUE TITLE
Feat: Add input for uploading banner

### ISSUE THREAD

**Issue by AshutoshDash1999** [SUGAM-ARORA/UniCollab#48]
**Is your feature request related to a problem? Please describe.**
The banner is static for now and hence can't be changed with new image.

**Describe the solution you'd like**
When someone will click on the existing banner a window will open to choose a file and select that banner.

**Additional context**
- The upload button will shifted to bottom right and  on top of banner.
- The max file size will be 2MB and minimum dimension should be  1600 x 400

Please assign this issue to me under GSSOC 24.

**Comment by SUGAM-ARORA** [comment]
@AshutoshDash1999 Issue has been assigned to you

**Comment by AshutoshDash1999** [comment]
@SUGAM-ARORA please review this PR: https://github.com/SUGAM-ARORA/UniCollab/pull/67

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA please review this PR: #67

Successfully merged it. Great work
