### ISSUE TITLE
Feat: Adding Github Login using Firebase

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#483]
### Describe the feature

@SUGAM-ARORA I want to add Github login in login page using firebase. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1c4830fd-3088-4f05-b00f-1c4d62811746)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
