### ISSUE TITLE
DOC: request to update the readme file

### ISSUE THREAD

**Issue by vedi9969** [SUGAM-ARORA/UniCollab#485]
### What's wrong with the existing documentation

I would like to update the readme file by adding setup and installation process like how they can clone the project, how to make PR in project and so  on many such things so the contributors can know how to do it. It will help many other who visits the project.  Below I've attached the image please refer it.
![2](https://github.com/user-attachments/assets/b7d7f80b-1aca-49c6-9136-728a7f241c4e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@vedi9969 This all is written in Contribute file
