### ISSUE TITLE
BUG: Website is down

### ISSUE THREAD

**Issue by SUGAM-ARORA** [SUGAM-ARORA/UniCollab#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

UniCollab website is down and is shown blank 
![Screenshot from 2024-07-18 00-24-07](https://github.com/user-attachments/assets/2fab72d5-9d37-4ffc-81cf-cffb2e341532)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Contributors who want to work on this please tell.

**Comment by SUGAM-ARORA** [comment]
Also the fix is of some lines but I would give level 3 since it is quite urgent and if response is late then level will go on decreasing

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA as of now, if we remove content from firebase.js, then the website is working perfectly fine.
![Uploading UniCollab.png…]()

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA  as of now, if we remove content from firebase.js, then the website is working perfectly fine.

![UniCollab](https://github.com/user-attachments/assets/61eeff48-f433-43e9-ba66-36c06dd9950c)

**Comment by AkshitGarg24** [comment]
For proper fixation of this code, you need to obtain the Firebase configuration from your end and paste it as attached.

![Firebase](https://github.com/user-attachments/assets/c4d11062-4fc5-4b79-904a-0a6fdc4d17ce)

**Comment by AkshitGarg24** [comment]
Now, how should I proceed with this issue?

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Great work . Actually you helped me in finding the firebase.js file which I was somehow not to find as maybe I didn't thought that file is in src

**Comment by SUGAM-ARORA** [comment]
Moreover I have completed solved this issue

**Comment by AkshitGarg24** [comment]
It's my pleasure, @SUGAM-ARORA!

**Comment by SUGAM-ARORA** [comment]
> It's my pleasure, @SUGAM-ARORA!

@AkshitGarg24 If you want I can change level of any of your old merged PR as a reward for this.

**Comment by AkshitGarg24** [comment]
It's purely your decision @SUGAM-ARORA, whatever you feel right, you can do that.

Moreover, if you decide to reward me, I have recently opened PR #495, so you can reward me there if you want.

**Comment by MinavKaria** [comment]
> @AkshitGarg24 Great work . Actually you helped me in finding the firebase.js file which I was somehow not to find as maybe I didn't thought that file is in src

You should have texted me , I would immediately replied you , bcoz I only had integrated firebase in the website, instead of struggling so much 😅
