### ISSUE TITLE
Feat: Adding Animations in social media's icons i footer

### ISSUE THREAD

**Issue by upsaurav12** [SUGAM-ARORA/UniCollab#509]
### Describe the feature

I want to add features llike transitions on social medias like ``linkedin`` ``github`` ``twitter`` etc 

### Add ScreenShots

![Uploading image.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Issue assigned to you
