### ISSUE TITLE
[BUG] Fix the Notification Button

### ISSUE THREAD

**Issue by yashmandi** [SUGAM-ARORA/UniCollab#51]
**Describe the bug**
When the user clicks on notification icon, nothing happens, some sort of drop-down should appear and display the notifications.

**To Reproduce**
Tap on Notification icon on Navbar

**Additional context**
Would like to work on this issue under GSSoC '24. Request you to assign the task :)

**Comment by mtg718** [comment]
Please assign this task to me.
I would like to work on this issue under GSSoC'24.

**Comment by SUGAM-ARORA** [comment]
@yashmandi Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
@mtg718 Issues are assigned on first come first serve basis.
You can look for issues from issue section. Moreover you can look for new features from [AIM_OF_THIS_PROJECT.md](https://github.com/SUGAM-ARORA/UniCollab/blob/main/AIM_OF_THIS_PROJECT.md) file under the key features section.

**Comment by SUGAM-ARORA** [comment]
Successfully merged.
