### ISSUE TITLE
BUG:footer is not appropriate

### ISSUE THREAD

**Issue by siddhant-2002** [SUGAM-ARORA/UniCollab#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/12191e02-1a37-45c5-a490-b7ca794adb96)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@siddhant-2002 This issue is already taken
