### ISSUE TITLE
Feat: Embed Firebase Auth Code for Handling User Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#511]
### Describe the feature

@SUGAM-ARORA I want to Embed Firebase Auth Code for Handling User Authentication in the website. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-06 002207](https://github.com/user-attachments/assets/d2ff7cef-7c18-4918-8b48-df7621ac9361)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assign to you
