### ISSUE TITLE
Change the position of "Subscribe to Newsletter"

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The position of "Subscribe to Newsletter" should be changed as the footer is occupying a lot of space because of it. There is also a lot of space on the left and right.

![UniCollab](https://github.com/user-attachments/assets/65291e22-a909-4627-96f1-bff79743aa0d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 issue assigned to you
