### ISSUE TITLE
Feat: Connecting Cart Icon to Cart Page

### ISSUE THREAD

**Issue by SUGAM-ARORA** [SUGAM-ARORA/UniCollab#514]
### Describe the feature

Cart Icon in Main Page is not connected to the Cart Page. Any contributor who wants to work on this issue I will assign him. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/178524b5-faaf-4d2f-811d-7dbf818871ab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA , I want some clarity in this issue. What I have understood is I have to make a Cart page and connect it with this icon. If so, then can you please tell me what type of design do you want in this cart's page.
