### ISSUE TITLE
Feat: Implementation of Feedback form

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#515]
### Describe the feature

A feedback form should be included on the website to take proper reviews and suggestions from various users.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
