### ISSUE TITLE
BUG: Improvment in Signin/Signup form in mobile view

### ISSUE THREAD

**Issue by upsaurav12** [SUGAM-ARORA/UniCollab#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the Sign-in/Sign-up page is not responsive for mobile view 

https://github.com/user-attachments/assets/24cea351-3a73-4a60-9c30-f62ca9b8fef4

Improvment in Sign-up/ Sign-in Form

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Issue assigned to you
