### ISSUE TITLE
Feat: Adding Phone Number Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#518]
### Describe the feature

@SUGAM-ARORA I want to add Phone Number Authentication Using Firebase. Kindly assign this issue to me.

### Add ScreenShots

![Screenshot 2024-07-14 181023](https://github.com/user-attachments/assets/78eb7cce-0eac-4258-a6b9-292beb3d1472)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
