### ISSUE TITLE
BUG:  The Trail Effect Should Hide in Mobile View

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [SUGAM-ARORA/UniCollab#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

The cursor Trail effect should be hidden in the mobile devices as we don't need any cursor there for actions we touch on the screens
the trail effect is causing bugs in mobile view:

https://github.com/user-attachments/assets/bbb99dc6-4f4e-4c63-90d8-9598234ac7b8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@RadhikaMalpani1702 Issue assigned to you
