### ISSUE TITLE
BUG: Overlapping sidebar menu and dropdown menu

### ISSUE THREAD

**Issue by techy4shri** [SUGAM-ARORA/UniCollab#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

There are two sidebar menus and both of them overlap. The first one which is fixed does not expand and a user can only know what the icons mean if they hover their pointer on the icons. The second menu is a dropdown one with slightly different options.

My suggestion is to merge them both into one and make it so that the sidebar menu expands and collapses. This will improve user experience and overall funcitnality of the website.
![Screenshot 2024-07-22 194651](https://github.com/user-attachments/assets/463c0783-0948-4342-8ee5-602ac78d4f77)

Contributing under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@techy4shri Issue assigned to you
