### ISSUE TITLE
BUG: The filtered options in search don't open

### ISSUE THREAD

**Issue by techy4shri** [SUGAM-ARORA/UniCollab#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The searched items which show as the result don't take the user to the item so the search is useless except telling whether there are projects similar to what I am searching.
The searched items should link to the project they name instead of just showing whether there are similar items because then the user has to search for the project all over again.

![Screenshot 2024-07-22 194813](https://github.com/user-attachments/assets/cdaf26f7-9f44-4868-8e15-32ca36ce7704)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@techy4shri Issue assigned to you
