### ISSUE TITLE
BUG: Feedback button and Scroll to top buttons are Overlapping

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

The Feedback button and Scroll to top buttons are Overlapping

![image](https://github.com/user-attachments/assets/b7fe9e98-cd00-4806-8c1c-4cb4a0c581c5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@MastanSayyad Issue assigned to you
