### ISSUE TITLE
BUG: Responsiveness of Footer

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The footer is not responsive to all the devices.

https://github.com/user-attachments/assets/fbc0dc33-f713-4437-a3fd-b25ad75b35d2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
