### ISSUE TITLE
DOC:Update the learn.md

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [SUGAM-ARORA/UniCollab#536]
### What's wrong with the existing documentation

As your app is dockerize and also have kubernetes so i want to update learn.md for this so that user feel easy to run this ap through docker and kubernetes

### Add ScreenShots

no screenshot neede

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@agarwalhimanshugaya Issue assigned to you
