### ISSUE TITLE
Feat:Want to improve Backend of Contact Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#537]
### Describe the feature

@SUGAM-ARORA I want to set up Backend of Contact Page. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-22 225454](https://github.com/user-attachments/assets/37b4760e-ab9a-4de8-849c-cf347ad9eb7a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
