### ISSUE TITLE
Feat: Enhancing the Design of The 'Help Us Improve' Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#544]
### Describe the feature

@SUGAM-ARORA I want to improve the styling of 'Help Us Improve' Page. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/40dcebb2-6f6a-4650-9aef-bfe81470d53c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
