### ISSUE TITLE
Feat: Adding Home Button in "Help Us Improve!" page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#545]
### Describe the feature

While implementing this page, I forgot to add a Home button which is available in all other web-pages.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
