### ISSUE TITLE
Feat: Implementing a "Rate-Us" page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#546]
### Describe the feature

In Footer, under Product category, there is a Rate-Us option but the page for that option has not been implemented yet.

### Add ScreenShots

https://github.com/user-attachments/assets/9b331b28-918e-464c-9fd8-5ab4435e9fff

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
