### ISSUE TITLE
Feat: Adding Facebook Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#547]
### Describe the feature

@SUGAM-ARORA I want to add Facebbok Authentication using Firebase. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-14 181023](https://github.com/user-attachments/assets/c88905a5-f820-4ea0-8c5c-edd7d769fccc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
