### ISSUE TITLE
Important Fix in Readme.md

### ISSUE THREAD

**Issue by say-het** [SUGAM-ARORA/UniCollab#55]
**Description**

- Issue is that without using npm install you cannot do npm start.
- While Contributing this might confuse new contributors.

 - I have already fixed the instruction.

Please @SUGAM-ARORA assign me this issue under GSSoC'24 so that I can raise a PR.

Little about me : I am experienced contributor as I have completed _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

**Comment by SUGAM-ARORA** [comment]
@say-het I have already updated the README file. Now you can for this from [LEARN.md](https://github.com/SUGAM-ARORA/UniCollab/blob/main/LEARN.md) file.
If you feel any changes in LEARN.md file  Let me know
