### ISSUE TITLE
Feat: Enchancing the Design and Styling of the Cart Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#550]
### Describe the feature

@SUGAM-ARORA I want to make changes to the Cart Page in terms of it s styling and design. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/af01b433-6f33-4407-9f1a-55e810d8c719)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
