### ISSUE TITLE
Feat: Adding Twitter Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#552]
### Describe the feature

@SUGAM-ARORA I want to add Twitter Authentication . Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-14 181023](https://github.com/user-attachments/assets/c5da427b-312f-45be-8c39-12d6a6d77e04)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
