### ISSUE TITLE
Feat: Adding Microsoft Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#554]
### Describe the feature

@SUGAM-ARORA I want to add Microsoft Authentication to the website. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-14 181023](https://github.com/user-attachments/assets/24c58c3b-06fc-4da6-ab8d-75ee514980fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
