### ISSUE TITLE
BUG: Reducing Font Size of Dropdown in Contact-Us Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The font size of the dropdown in the Contact Us Page should be reduced for a better view. I know I have already been assigned 3 issues, but they are small issues and won't take too much time. I request you to assign me this issue as well kindly.

![DropDown](https://github.com/user-attachments/assets/620c02bf-0fed-4115-a117-a73539d0220f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
