### ISSUE TITLE
Feat: Adding LinkedIn Authentication

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#560]
### Describe the feature

@SUGAM-ARORA I want to add LinkedIn Authentication to the website. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-14 181023](https://github.com/user-attachments/assets/46f4bdef-4150-443a-af13-b630152e43f2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
