### ISSUE TITLE
BUG: Footer

### ISSUE THREAD

**Issue by Meetjain1** [SUGAM-ARORA/UniCollab#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently copyright year is direct copy paste of text or we can say static , But it should be dynamic that is it should auto fetch the current year.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Meetjain1 Issue assigned to you
