### ISSUE TITLE
BUG: Fixing Sign-Up Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The UI of the Sign-Up page should be fixed.

![Screenshot 2024-07-25 233731](https://github.com/user-attachments/assets/631ca2de-c897-479f-9a4a-0ac975996c19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
