### ISSUE TITLE
BUG: Fixing Login Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The UI of the Login page should be fixed.

![Screenshot 2024-07-25 233959](https://github.com/user-attachments/assets/6aabb8b8-e389-4932-a56f-75ec710d36cc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
