### ISSUE TITLE
BUG: Making Sign-out button functional

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

On clicking the sign-out button, it should show a pop-up showing "Successfully signed out".

![Sign-out](https://github.com/user-attachments/assets/518d39e6-4ea0-4346-81a5-48e86067cca5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
