### ISSUE TITLE
Follow Button

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

On clicking the Follow button, it should show "Following". It should be a toggle button i.e. on clicking this button, it should toggle between "Follow" and "Following".

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
