### ISSUE TITLE
Feat: Implement Popular Page to Highlight Trending Content

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#577]
### Describe the feature

@SUGAM-ARORA I want to add the popular section in the website. Kindly assign me this issue.

### Add ScreenShots

![Screenshot (2)](https://github.com/user-attachments/assets/d5fd5d53-4f4c-419e-8414-85769072078e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
