### ISSUE TITLE
Feat: Enhance the README File

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#584]
### Describe the feature

@SUGAM-ARORA I want to do some updations in the README File to make it better. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5241a48e-20aa-470a-a881-20200ba34fae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
