### ISSUE TITLE
DOC:Comprehensive Documentation Update

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#585]
### What's wrong with the existing documentation

@SUGAM-ARORA I want to do the Comprehensive Documentation Update: Implementing Firebase Features, Backend for Contact Page, Help Us Improve Page, Cart Page, and Feedback Form etc. Kindly assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
