### ISSUE TITLE
Feat: Improvement of UI in contact us page 

### ISSUE THREAD

**Issue by upsaurav12** [SUGAM-ARORA/UniCollab#587]
### Describe the feature

Currently the UI of contact-us page looks like this
![image](https://github.com/user-attachments/assets/f32136e7-d7b5-418b-b62c-08caacf119a8)

We can improve its UI and make it better

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f32136e7-d7b5-418b-b62c-08caacf119a8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by upsaurav12** [comment]
Hi @SUGAM-ARORA i have done some work on this issue
and it is looking like this 
![image](https://github.com/user-attachments/assets/ec1ccdf7-41e0-4555-9827-fb0828fa35ad)

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Kindlhy don't change the ui of contact page. It looks better before
