### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by SwanandD121** [SUGAM-ARORA/UniCollab#59]
**Problem**
The website lacks a favicon, which diminishes its professional appearance and branding consistency. A favicon is a small but essential element that appears in the browser tab and bookmarks, helping users quickly identify and navigate to the website.

**Solution**
Adding the favicon which will be the logo of the website.

Please assign me this issue under GSSoC'24.

**Comment by SUGAM-ARORA** [comment]
@SwanandD121 Issue assigned to you

**Comment by SwanandD121** [comment]
> @SwanandD121 Issue assigned to you

Favicon added and PR created!

**Comment by SUGAM-ARORA** [comment]
Merged
