### ISSUE TITLE
Feat:Improve FAQ page UI 

### ISSUE THREAD

**Issue by upsaurav12** [SUGAM-ARORA/UniCollab#590]
### Describe the feature

Currently the FAQ Page looks like this 
![image](https://github.com/user-attachments/assets/8e8cadd7-dfb1-49b0-aa0b-f1c27884d249)
WE can take some ideas from the ``internet`` as an aspiration 

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Not needed

**Comment by upsaurav12** [comment]
![image](https://github.com/user-attachments/assets/fcfc5604-5e50-4bca-b3e3-e2217b9f7952)
May be we can improve the page later

**Comment by SUGAM-ARORA** [comment]
> ![image](https://private-user-images.githubusercontent.com/116784047/352714831-fcfc5604-5e50-4bca-b3e3-e2217b9f7952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzU0MjEsIm5iZiI6MTcyMjA3NTEyMSwicGF0aCI6Ii8xMTY3ODQwNDcvMzUyNzE0ODMxLWZjZmM1NjA0LTVlNTAtNGJjYS1iM2UzLWUyMjE3YjlmNzk1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QxMDEyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2RjY2JmZDIwN2VmMDNlZTEzNDMwNjMzYjdhNGYyMzc4NTVkYTdmZDY2M2FkNjg0NDBkZDZhY2VhNDZkYTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F9z_KDJZm7KCOloWVbQyO1Pyet0t_NhWghtRWoRvutY) May be we can improve the page later

Yes. Plus the blue shadow is great. Don't remove that
