### ISSUE TITLE
Feat: Improve Our Blogs page 

### ISSUE THREAD

**Issue by upsaurav12** [SUGAM-ARORA/UniCollab#593]
### Describe the feature

Currently Blogs Page  looks like this 
![image](https://github.com/user-attachments/assets/235fe535-1aab-4c6b-ade8-d2fffd8f95d2)
We can improve this page by better styling and UI

### Add ScreenShots

![image](https://github.com/user-attachments/assets/559d55b2-b380-4966-8c73-e38992bbd8b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Can you share some image or something so that I can get to know what enhancement you would do?

**Comment by upsaurav12** [comment]
Page that gave i gave you For Blog. Currently the box shadow is not looking good with the theme so be can remove that

**Comment by JaiSharma1710** [comment]
hi @SUGAM-ARORA  i have created pr improving the page design, please have a look and let me know if any changes is required.
