### ISSUE TITLE
NOT GOOD for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [SUGAM-ARORA/UniCollab#598]
### Describe the feature

![image](https://github.com/user-attachments/assets/5a0afebb-867b-4a9a-a594-4eae72ae5d01)

### Add ScreenShots

It should be made to look proper spacing and uniform design to have a better professional look

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Utsavladia Issue assigned to you
