### ISSUE TITLE
Changing twitter bird logo to X

### ISSUE THREAD

**Issue by Ketanop321** [SUGAM-ARORA/UniCollab#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Please give this issue a level one1😭😭🙏

![image](https://github.com/user-attachments/assets/7692e3c0-ae99-45b8-bbd6-e32a1907c5c7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ketanop321** [comment]
@SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 Issue assigned to you
