### ISSUE TITLE
Girlscript Summer of Code Introduction/Tracking

### ISSUE THREAD

**Issue by Princegupta101** [SUGAM-ARORA/UniCollab#6]
👋 Hi @SUGAM-ARORA ,

I am Prince,web developer Girlscript Summer of Code. I'll be collaborating with you on preparing your repo for GSSoC'24 Program

Why are these changes required?
After Analysing last year's contributions and feedback it would be great for students to have a couple of standard readme files on the repo to understand what the project is all about and some issues detailing what they can contribute. This will help you to see increased engagement in your repository as well.

As mentioned students get a chance to learn step by step, how to build this project as well as invite mentors to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for Girlscript summer of code 2024 on 10th May.

This issue will serve as a tracking issue to track all issues related to GSSoC'24. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat:

- [x] #1
- [x] #2
- [x] #3 
- [x] #4
- [x] #5

**Comment by vix2704** [comment]
Hello sir...I'm interested in contributing to this project under Gssoc 2024 program, kindly assign it.

**Comment by SUGAM-ARORA** [comment]
Hello @Princegupta101 
I have updated the readme file with the requirements of  this  project. Moreover I will update the 5 issues raised by you.

**Comment by ridhi-ahuja** [comment]
Hello , as a Contributor in GS'SOC 2024 I am looking forward on working and contributing in this project as per my interest .it would enhance and upgrade my technical skills.
I've developed skills in JAVA , C , Java script ,Python , WEB development and basic Machine Learning ,currently under Artificial Intelligence training on implementing AI tools ,exploring more in tech.

**Comment by SUGAM-ARORA** [comment]
Hello @vix2704 @ridhi-ahuja. You can look for issues from issue section. Moreover you can look for new features from [AIM_OF_THIS_PROJECT.md](https://github.com/SUGAM-ARORA/UniCollab/blob/main/AIM_OF_THIS_PROJECT.md) file under the key features section.
