### ISSUE TITLE
Feat: Implementation of Speed Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#602]
### Describe the feature

@SUGAM-ARORA I want to mahe the speed page in the menu. Kindly assign me this issue.

### Add ScreenShots

![Screenshot (2)](https://github.com/user-attachments/assets/2f927644-006d-479d-8465-617212b123ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
