### ISSUE TITLE
BUG: Background color of "Top Contributor" 

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The background color of the "Top Contributor" section should be changed.

![Top Contributor](https://github.com/user-attachments/assets/e0329a11-e84a-42f6-93d3-3877be9fe001)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
