### ISSUE TITLE
BUG: Adding Hover options on Card in Cart Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The cards on the cart page lack hover options, which should be implemented.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you
