### ISSUE TITLE
Implementing Wallet Page

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I wish to implement a Wallet Page for the website. But I don't have any great idea of what should be implemented in this web page.
So if you provide me a few details about this page, it will be easy for me to implement this page. Otherwise, I will implement it from my side.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA could you provide me some details on what should be included in this page?

**Comment by SUGAM-ARORA** [comment]
Something like e-commerce wallet . Basically we have points and rupees both in wallet. Points can be converted to rupees too like 1000 points = 50 rupees or something like that.
