### ISSUE TITLE
Feat: Adding Home icon in the Settings Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#610]
### Describe the feature

@SUGAM-ARORA I want to add home icon in the Setting Page. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2259a59a-b99b-47e0-908c-d561a6b6ad2e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
