### ISSUE TITLE
Format and Enhance Legal Pages: Privacy Policy, Terms and Condition, Licensing

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [SUGAM-ARORA/UniCollab#616]
### Describe the feature

Hey @SUGAM-ARORA 

I would like to format and properly align the legal pages in the same adjustment to ensure legal compliance

![image](https://github.com/user-attachments/assets/48324533-badf-46db-a68a-a30e254c64c1)

![image](https://github.com/user-attachments/assets/e03a0637-3d39-45c5-a88f-d7c0bafea44a)

![image](https://github.com/user-attachments/assets/e83fd206-e16f-4f05-bcae-4c21d9d56d76)

Additionally, the weight of the text is too heavy, the back-to-home page overlaps the text

![image](https://github.com/user-attachments/assets/855c6d20-e0ed-4d93-b6c5-42f0f21eb13e)

![image](https://github.com/user-attachments/assets/630797d4-177b-4e4e-8333-9aef96c0bcf8)

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@RadhikaMalpani1702 Issue assigned to you
