### ISSUE TITLE
Feat: Expandable Sidebar with Toggle Button

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#617]
### Describe the feature

@SUGAM-ARORA I want to make changes to the side menu in main page such that it toggles before and out. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/76ddbeca-5de3-4d69-8915-362eb5477ff3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
