### ISSUE TITLE
Feat: Sidebar Page Overlapping 

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#621]
### Describe the feature

@SUGAM-ARORA The sidebar Page is overlapping behind the navbar and the cards .  I want to fix this . Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9c9b133c-4371-49a8-9347-aa279a90f227)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
