### ISSUE TITLE
Feat: Making of Sort By Buttons

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#623]
### Describe the feature

@SUGAM-ARORA I want to make the buttons for Sort By. Kindly assign me this issue.

### Add ScreenShots

![Screenshot (2)](https://github.com/user-attachments/assets/1f4e9782-2e50-4da1-ac05-8f2275878869)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
