### ISSUE TITLE
Feat: Connecting Backend of Help Us Improve Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#628]
### Describe the feature

@SUGAM-ARORA I want to do the connection of backend in Help us improve Page. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6cf63113-e04b-4024-a9dc-08d559d82a26)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Although fully functional backend won't be there as I might need to make some changes in to let it work . You can do the other changes required for this

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Sir I had done till that only
