### ISSUE TITLE
Feat: Issue in styling in Career Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#632]
### Describe the feature

@SUGAM-ARORA I want to change styling of career page. Kindy assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4002bb79-f635-4773-a757-990a5d3af9ed)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Make sure not to make major edits in this
