### ISSUE TITLE
Feat: Setting the UI of Main Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#635]
### Describe the feature

@SUGAM-ARORA The UI of main page is not looking good. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6346673d-353e-450f-9207-d3922fc0c5af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you. Try to make it dynamic
