### ISSUE TITLE
Create Our Contributors Page for Unicollab

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [SUGAM-ARORA/UniCollab#637]
### Describe the feature

Hey @SUGAM-ARORA 

I would like to create and add contributors page matching to the website design theme for unicollab

and

### Add ScreenShots

![image](https://github.com/user-attachments/assets/99010f8a-6581-4347-ad00-a66f1c119469)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@RadhikaMalpani1702 Issue assigned to you

**Comment by RadhikaMalpani1702** [comment]
Hey @SUGAM-ARORA  I have created the page but I am unable to find the route to declare path in App.js and the page is showing 404 not found
