### ISSUE TITLE
Feat: Implementing Delicious Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#640]
### Describe the feature

@SUGAM-ARORA I want to make the Delicious Page in the sidebar. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-29 122411](https://github.com/user-attachments/assets/67f16b17-a976-40df-a771-46c5df733c41)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
