### ISSUE TITLE
Feat:Trending Now Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#641]
### Describe the feature

@SUGAM-ARORA @SUGAM-ARORA I want to make the Trending Page in the sidebar. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-29 122411](https://github.com/user-attachments/assets/42b20c9d-5623-4d75-95d3-b21412d65f47)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
