### ISSUE TITLE
BUG: Unresponsive Social Icons on login page

### ISSUE THREAD

**Issue by techy4shri** [SUGAM-ARORA/UniCollab#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The social icons on login page have no link, they do not direct the user anywhere and are thus useless. All except the last call icon which seems to give the user an option to log in via OTP. But it is not UX friendly. There should be a big button for that stating "LOGIN VIA OTP" .
![image](https://github.com/user-attachments/assets/d366e1db-7d3a-4b4e-ab11-a459a760e9e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What went down?
> The social icons on login page have no link, they do not direct the user anywhere and are thus useless. All except the last call icon which seems to give the user an option to log in via OTP. But it is not UX friendly. There should be a big button for that stating "LOGIN VIA OTP" . ![image](https://private-user-images.githubusercontent.com/141991095/354324633-d366e1db-7d3a-4b4e-ab11-a459a760e9e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzU1NTYsIm5iZiI6MTcyMjUzNTI1NiwicGF0aCI6Ii8xNDE5OTEwOTUvMzU0MzI0NjMzLWQzNjZlMWRiLTdkM2EtNGI0ZS1hYjExLWE0NTlhNzYwZTllMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODAwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjYzZDhkMGUxMzYzN2YwMTM4YWRkOTE2ODk3NGQ0OTAxZDZkNDMwYjY3MjRjZGIzZDU5MzBmZjk4NmZiYjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.716DMDkbU1uil9t55MigF9vp7tWK5RrQqa3VaoRTQw0)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

@techy4shri These links are not working because firebase from my end has not been configured . Contributor has although made the connections for this but it will be visible once i configure them on firebase
