### ISSUE TITLE
Feat: Recording Saving

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#650]
### Describe the feature

@SUGAM-ARORA I want to add an option for recording to be saved in the speed option. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-29 122411](https://github.com/user-attachments/assets/d11d906c-ab72-4b21-a839-590bf910f205)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you . Made the required changes in the code but the recording won't be save till backend is there.
