### ISSUE TITLE
Feat: UI Improvement

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#660]
### Describe the feature

@SUGAM-ARORA I want to set the UI for Wallet and Rate us page. Kindly assign me this issue.

### Add ScreenShots

![UniCollab-Bottom](https://github.com/user-attachments/assets/949a3835-fead-4d9d-b96a-4cb585945288)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
