### ISSUE TITLE
Feat: Rate us Backend

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#661]
### Describe the feature

@SUGAM-ARORA I want to set up the backend of Rate us page. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/22a5e5db-3d29-48e2-97d7-5dc309021248)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
