### ISSUE TITLE
Feat: Search Icon Position

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#667]
### Describe the feature

@SUGAM-ARORA The search Icon in navbar is not in the search Bar. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/039ab2d8-93bc-44db-b69b-9f83e2401356)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
