### ISSUE TITLE
Feat: Reset Password Page

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#670]
### Describe the feature

@SUGAM-ARORA I want to make a reset password Page in the Login Page. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-24 161324](https://github.com/user-attachments/assets/cfa688b8-3dda-4083-b594-a68cb63cffa8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
