### ISSUE TITLE
Feat: Portfolio Creation

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#674]
### Describe the feature

@SUGAM-ARORA I want to make Portfolio Page for UniCollab. Kindly assign me this issue.

### Add ScreenShots

![UniCollab-Bottom](https://github.com/user-attachments/assets/4658fd99-2f27-4dc1-a270-c96eca66d80c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
