### ISSUE TITLE
Feat: Type Of Projects

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#675]
### Describe the feature

@SUGAM-ARORA I want to make changes in the card by adding type of projects. Kindly assign me this issue.

### Add ScreenShots

![Screenshot (2)](https://github.com/user-attachments/assets/4563f0f7-4232-4965-9096-a9504ded8e98)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Make sure that type of project is in some box or something which looks similar to labels

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Ok sir
