### ISSUE TITLE
NOT GOOD Navbar sizings for alll sizes and going out of screen

### ISSUE THREAD

**Issue by Utsavladia** [SUGAM-ARORA/UniCollab#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/03a3081a-aa57-4f6e-b262-cbdcd920540d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Utsavladia Issue assigned to you
