### ISSUE TITLE
Feat: Want to add hamburger Menu 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [SUGAM-ARORA/UniCollab#678]
### Describe the feature

I want to add a hamburger menu which will be visible at the time of small screen

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fda798c2-d926-4dc5-bd78-1a6a6b20dd1f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ayushmaanagarwal1211 Issue assigned to you
