### ISSUE TITLE
Feat: Want to make the carriers sections fully responsive 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [SUGAM-ARORA/UniCollab#679]
### Describe the feature

I want to make the carriers section responsive 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4dc18f5a-f3c9-4df9-9ab2-52198bc9f709)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ayushmaanagarwal1211 Issue assigned to you
