### ISSUE TITLE
Feat: Popular Project Showcase

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#681]
### Describe the feature

@SUGAM-ARORA I want to set the type of projects in the popular page. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d441ec1f-927a-4a40-ac62-024bd9c6ed46)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
