### ISSUE TITLE
BUG: Incomplete Contributos list in Contributors Page

### ISSUE THREAD

**Issue by MastanSayyad** [SUGAM-ARORA/UniCollab#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

The GitHub API by default is showing 30 contributors only and not all contributors list 

![image](https://github.com/user-attachments/assets/2b9ab7dd-846a-455f-82fc-5258ed8fe7b6)

![image](https://github.com/user-attachments/assets/0c2291b5-14fc-4d98-b9d1-66a1b6bce13a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@MastanSayyad We need top 30 only
