### ISSUE TITLE
BUG: Components not aligned Properly for mobile devices

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The website is not looking good in mobiles and so i want to improve website's look and feel for mobile devices. 
Components are not properly aligned and also not are not of same size.

![Screenshot 2024-08-07 195853](https://github.com/user-attachments/assets/b8f85177-17c2-46e8-b336-25c743446977)
![Screenshot 2024-08-07 195907](https://github.com/user-attachments/assets/71941f8a-66d6-4294-88fb-d5eeca7aff69)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you

**Comment by saketh-05** [comment]
@SUGAM-ARORA I have completed this work and will create Pull request tomorrow early in the  morning.

**Comment by saketh-05** [comment]
@SUGAM-ARORA I am currently working with the implementations of various projects and how should they be portrayed in the website so that everyone can see projects source code and also use them. I will raise issues and also create pr for implementation of projects as only 2 days are left to contribute.

**Comment by saketh-05** [comment]
Thank you for assigning me this issue.
