### ISSUE TITLE
Feat: Sort feature for Projects in home page

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#686]
### Describe the feature

I want to add sort functionality for projects in the home page. This will provide better look and feel for the website and also projects can be shown dynamically.

### Add ScreenShots

![Screenshot 2024-08-08 164037](https://github.com/user-attachments/assets/1c2cda5e-332d-40e4-af2c-4047347eeff2)
![Screenshot 2024-08-08 164049](https://github.com/user-attachments/assets/3f51c731-e014-4117-a304-d47ad810c573)
![Screenshot 2024-08-08 164102](https://github.com/user-attachments/assets/2286507c-8328-4775-9734-cbe24aebc53d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you
