### ISSUE TITLE
Feat: Type Icon

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#688]
### Describe the feature

@SUGAM-ARORA I want to add the type icon dropdown in the Page. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-08-07 163317](https://github.com/user-attachments/assets/b45725b0-9335-4cd3-a393-c4b7d77b3bae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
