### ISSUE TITLE
Feat: Improve UI of projects page and Provide correct integration

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#698]
### Describe the feature

The cards in the projects page are not correctly integrated with their respective images and links. I want to fix this and also it is not looking so attractive and I want to improve look and feel also.

### Add ScreenShots

![Screenshot 2024-08-09 085458](https://github.com/user-attachments/assets/b2e719b3-450c-4e8a-aa44-a5d2a0074bbf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you
