### ISSUE TITLE
Feat: want to add a hover effect in the navbar 

### ISSUE THREAD

**Issue by gangwarsomya** [SUGAM-ARORA/UniCollab#699]
### Describe the feature

![image](https://github.com/user-attachments/assets/0a61c661-6cd6-4317-8425-4f1d25223a73)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0cd7df5b-2901-4de6-8894-34077b3914b5)
here the nav bar is not proper visible  and hove effect is not even

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@gangwarsomya This issue not needed
