### ISSUE TITLE
BUG: Without Login the Logout button is visible 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [SUGAM-ARORA/UniCollab#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I am not logged in but still i can see the Log out button 

https://github.com/user-attachments/assets/454d96bd-feb8-49ed-803c-c8622a9ea349

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ayushmaanagarwal1211 Issue assigned to you

**Comment by MohammedJunaid02** [comment]
Hi @SUGAM-ARORA, can i start working on this issue , because this issue is open since so long and no one has worked on this, so shall i go ahead and start working on this?

**Comment by MohammedJunaid02** [comment]
Hi @SUGAM-ARORA, can you please update..??

**Comment by SUGAM-ARORA** [comment]
@MohammedJunaid02 yes you can work on this!

**Comment by MohammedJunaid02** [comment]
OK, @SUGAM-ARORA, please assign this issue to me, I have already started working on this. Please assign this to me under HacktoberFest - 2024 as I want to solve this under that. 
Thank You

**Comment by MohammedJunaid02** [comment]
Hi @SUGAM-ARORA , I have fixed this issue and raised a pull request for the same. Please assign this issue to me.


Demonstration for the changes done:

https://github.com/user-attachments/assets/0c9d9ea9-b889-4899-abdd-a067b121874b


PR Link: https://github.com/SUGAM-ARORA/UniCollab/pull/811
Review the code changes in the Pull Request and merge it.
Thank You

**Comment by MohammedJunaid02** [comment]
Gentle Reminder.! @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
> Gentle Reminder.! @SUGAM-ARORA

Thanks !! Appreciated

**Comment by MohammedJunaid02** [comment]
Hi @SUGAM-ARORA 
I can see that you have merged my PR to fix this issue, in that case, Can you please close this issue, so that others know that this is already fixed giving a room of space to others to look at other open issues,  Hope you understand. 😀
Thank You.!!
