### ISSUE TITLE
Feat: Navbar Problem

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#709]
### Describe the feature

@SUGAM-ARORA Navbar is not properly visible and also the same for toggle button colors . kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/680bd06d-13a6-43db-89e2-5e04c4c4e7d7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
