### ISSUE TITLE
Feat: Implementation of WeatherLy Project 

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#714]
### Describe the feature

I want to Implement the WeatherLy Project in the website. This will be added attraction to the website as the projects can be tested/used by users.

### Add ScreenShots

![Screenshot 2024-08-10 113813](https://github.com/user-attachments/assets/4c37202d-d5ba-4d2e-b9f9-687cb6da95a8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you
