### ISSUE TITLE
Feat: Implementaion of Typing Test Project

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#715]
### Describe the feature

This project is entirely made using HTML, CSS, JS. I want to Implement the Typing Test Project in the website. This will be added attraction to the website as the projects can be tested/used by users.

### Add ScreenShots

![Screenshot 2024-08-10 102852](https://github.com/user-attachments/assets/b155043d-52f0-4862-b05e-cb8cecb35222)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you
