### ISSUE TITLE
Feat: Implementing Dev Note-Taking App

### ISSUE THREAD

**Issue by saketh-05** [SUGAM-ARORA/UniCollab#717]
### Describe the feature

The developer note taking app can be implemented and added to the website. This will be good added attraction.

### Add ScreenShots

![Screenshot 2024-08-10 125313](https://github.com/user-attachments/assets/f461a311-aad6-4e4b-b31e-47c92a89f148)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Issue assigned to you
