### ISSUE TITLE
Feat: Toggle Theme Color

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#718]
### Describe the feature

@SUGAM-ARORA I want to change the color of Toggle theme. Kindly assign me this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/965ae77f-c5f3-4169-aac3-2f51d1c0bd9f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
