### ISSUE TITLE
Feat: Different Colours Icons Naving

### ISSUE THREAD

**Issue by Ojas-Arora** [SUGAM-ARORA/UniCollab#721]
### Describe the feature

@SUGAM-ARORA I want to add toggle to the nvbar also. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-08-10 154208](https://github.com/user-attachments/assets/cec75331-2e71-4211-a08d-5b1b297a313a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you
