### ISSUE TITLE
NOT GOOD Navbar for mobile screen 

### ISSUE THREAD

**Issue by Utsavladia** [SUGAM-ARORA/UniCollab#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/217c6a94-950a-4378-bb3c-6eb7bb4b170f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Utsavladia Issue assigned to you

**Comment by Utsavladia** [comment]
@SUGAM-ARORA 
Kindly merge this before GSSOC ends 😌
