### ISSUE TITLE
[FEATURE] Implement Footer Section

### ISSUE THREAD

**Issue by yashmandi** [SUGAM-ARORA/UniCollab#74]
**Is your feature request related to a problem? Please describe.**
The website lacks a consistent footer across all pages, making it difficult for users to find important links and navigate effectively. 

**Describe the solution you'd like**
I would like to have a footer added to website that appears at the bottom of every page. This footer should contain essential links, such as contact information, terms of service, privacy policy, and social media links, to improve user navigation and experience.

**Additional context**
Would like to work on this task under GSSoC '24. Request you to assign this task to me :)

**Comment by SUGAM-ARORA** [comment]
@yashmandi Issue assigned to you
