### ISSUE TITLE
Hover effect on buttons

### ISSUE THREAD

**Issue by Ishmeetkaur36** [SUGAM-ARORA/UniCollab#75]
Adding hover effects to buttons could enhance them more

You can assign this issue to me @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
Could you please specify which buttons you are referring to? @Ishmeetkaur36

**Comment by Ishmeetkaur36** [comment]
![Screenshot 2024-05-16 224905](https://github.com/SUGAM-ARORA/UniCollab/assets/164319173/a4a0f3cf-ac12-42ab-9f39-32ce74d27bc4)
![Screenshot 2024-05-16 225134](https://github.com/SUGAM-ARORA/UniCollab/assets/164319173/70df6ca9-5db1-4816-897f-cb84fb394c09)

adding transition hover effects to these  @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@Ishmeetkaur36 Issue assigned to you
