### ISSUE TITLE
BUG: Alignment of Home icon in small screen devices, some UI fixes

### ISSUE THREAD

**Issue by Prithwi32** [SUGAM-ARORA/UniCollab#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in pricing page in home icon  UI fix
![Screenshot 2024-10-01 012832](https://github.com/user-attachments/assets/a9948519-0fa5-408a-ab7d-de2a2c16ed31)

in Help us Improve page home icon UI fix
![Screenshot 2024-10-01 013431](https://github.com/user-attachments/assets/c7cd1e10-0cb2-4b37-993b-3d04b424e54d)

![Screenshot 2024-10-01 013555](https://github.com/user-attachments/assets/eec001fd-5b2f-4197-99a8-e601ad45d721)
I would like to correct UI for help us improve form in light mode, placeholder dark looking odd!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@IAlgorithmia please could you assign this issue to me

**Comment by IAlgorithmia** [comment]
Hey @Prithwi32, I think you should try asking @SUGAM-ARORA since he is the maintainer here :)

**Comment by Prithwi32** [comment]
> Hey @Prithwi32, I think you should try asking @SUGAM-ARORA since he is the maintainer here :)

Okay.. thank you for information 🙂
@SUGAM-ARORA please could u assign this task to me under hacktoberfest

**Comment by coder-pink** [comment]
@SUGAM-ARORA Hi, Can you assign this issue to me

**Comment by SUGAM-ARORA** [comment]
@Prithwi32 Issue assigned to you
