### ISSUE TITLE
Feat: Adding Relaxio Chrome extension project

### ISSUE THREAD

**Issue by Winter262005** [SUGAM-ARORA/UniCollab#787]
### Describe the feature

I have created a Chrome extension which works on all Chromium-based browsers for stress relief when coding.

Features:
- Motivational Quotes on a single click,
- Meow! button which fetches random funny cat photographs and GIFs,
- A simple number guesser game and
- A custom tailormade collection of LoFi beats for concentration.

This Chrome extension works using the Manifest feature of chromium browsers, Html, CSS and JavaScript, and using various APIs (Quotable for quotes, TheCatApi for cat images, Music from FreeSoundLibrary).

Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest
Thank You

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b4ca8d6a-5d51-4165-a480-8dbb52eb5e69)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Winter262005** [comment]
Hey! @SUGAM-ARORA 
I have this project up and running. Just assign this project to me under gssoc24 extended and hacktoberfest, and i'll link a PR to this issue on the same day.

**Comment by SUGAM-ARORA** [comment]
@Winter262005 Issue assigned to you

**Comment by Winter262005** [comment]
Hey! @SUGAM-ARORA 
PR linked!
also can you also add the gssoc24 extd tags too
thank you
