### ISSUE TITLE
Feat:gemini chatbot

### ISSUE THREAD

**Issue by sp9324** [SUGAM-ARORA/UniCollab#791]
### Describe the feature

Issue #117

## Description
Integrated a chatbot using Gemini API. More accuracy than previous chatbot. This friendly assistant answers general queries related to tech, development and open source.

## Type of Issue

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

### Add ScreenShots

Preview: https://drive.google.com/file/d/13MI0wKSTJL3GedRiiwr36BaSVdTJBfkX/view?usp=sharing

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@sp9324 Issue assigned to you
