### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [SUGAM-ARORA/UniCollab#8]
repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

**Comment by AMANVISHWAKARMA27** [comment]
@SUGAM-ARORA , Kindly assign me this issue.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by SUGAM-ARORA** [comment]
@anshgautam-github are you up for this? 
Or should I assign this to someone else.

**Comment by ayoush-kumar** [comment]
@SUGAM-ARORA could you plese assign me this issue ?

**Comment by suhanipaliwal** [comment]
If no one is working on this issue, could you please assign it to me.

**Comment by Braj-01** [comment]
@SUGAM-ARORA Pls assign me this issue I have a prior experience.

**Comment by n14rishitha** [comment]
Hi @SUGAM-ARORA 
CONTRIBUTING.md file is more important for the contributors who visited this repo and who are at the begging stage of contributing .I would like to work on this issue . so please assign this task to me under the label gssoc24 and level 1,2,or 3

**Comment by SUGAM-ARORA** [comment]
@anshgautam-github Issue assigned to you

**Comment by abhishekdumaniya** [comment]
I want to add this file CONTRIBUTING.md to the contributor. I can help with this as well @SUGAM-ARORA can you assign me under GSSOC 24?

**Comment by anshgautam-github** [comment]
@SUGAM-ARORA  thank you.

**Comment by SUGAM-ARORA** [comment]
@abhishekdumaniya Issues are assigned on first come first serve basis

**Comment by suhanipaliwal** [comment]
@SUGAM-ARORA I think you should start assigning this issue to the next person because this issue has been open from a long time and the current assignee has still not worked on it.

**Comment by SUGAM-ARORA** [comment]
@suhanipaliwal Generally 1-2 week time is given to each contributor for each issue to resolve. Let's wait till then.

**Comment by ayoush-kumar** [comment]
he is taking so long this work can be completed with in 1-2 hrs can you please assign me ?? I'll do it by the end of the day

**Comment by anshgautam-github** [comment]
@SUGAM-ARORA  Sorry for the delay, I will finish it tonight , some emergency came that's why I was not able to finish it .
