### ISSUE TITLE
Add Hover Effect with Transition on Cards

### ISSUE THREAD

**Issue by AkshitGarg24** [SUGAM-ARORA/UniCollab#80]
The cards on the website currently lack a hover effect, which makes the user experience less engaging. To improve the visual appeal and interactivity of the website, I will implement a scaling effect on the cards when they are hovered over, using CSS transitions. This will make the website more dynamic and visually appealing. Kindly label this issue and assign this issue to me.
![Screenshot 2024-05-17 011624](https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/277cc944-10b3-4631-ac18-c6c38ab4bc34)

**Comment by JagjeetChauhan** [comment]
Hey can you assign this task to me under gssoc'24

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24  Kindly add the issue number . 
Like this 
Fixes #Issue_number
