### ISSUE TITLE
Feat: UI for the footer and card component on the freelancer page

### ISSUE THREAD

**Issue by Am26-Dev** [SUGAM-ARORA/UniCollab#809]
### Describe the feature

Hey @SUGAM-ARORA The  card component at the end is partially hidden behind the footer, causing a layout issue. The footer overlaps the card, making it not fully visible. Additionally, on full screen, the profile cards are not aligned properly.  Can please mark this under hacktober 2024, and assign it to me to solve this issue.

### Add ScreenShots

![Screenshot-1](https://github.com/user-attachments/assets/78632623-d316-44c2-8a94-58e95f1242a5)

![Screenshot-2](https://github.com/user-attachments/assets/897fc7e0-6db3-4a5d-a3e1-3f62e4504148)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuprHUlk** [comment]
@SUGAM-ARORA @Am26-Dev if this issue is still available can I work on the solution?

**Comment by Am26-Dev** [comment]
@SuprHUlk this issue hasn't been assigned to me yet. To fork and contribute, the issue needs to be assigned first.

**Comment by SUGAM-ARORA** [comment]
> @SuprHUlk this issue hasn't been assigned to me yet. To fork and contribute, the issue needs to be assigned first.

It is not necessary that issue is to be assigned first and then you can fork and contribute.

**Comment by SUGAM-ARORA** [comment]
You can start working on the issue and then it will be assigned in sometime
