### ISSUE TITLE
Feat: The UI of the About section

### ISSUE THREAD

**Issue by Shrivastava-04** [SUGAM-ARORA/UniCollab#818]
### Describe the feature

Hey @SUGAM-ARORA the UI in the about section seems boring with the minimal animation and the absence of navbar which make user difficult to go from about page to another page directly.

### Add ScreenShots

![Screenshot 2024-10-17 193612](https://github.com/user-attachments/assets/496602bf-1df8-41a7-8122-b7082a0e7bce)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@Shrivastava-04 Issue not needed
