### ISSUE TITLE
Update the UI of contact page

### ISSUE THREAD

**Issue by SuprHUlk** [SUGAM-ARORA/UniCollab#820]
### Describe the feature

The UI of contact page looks very unaligned 

Example
" Contact us at : " and "+91 1234567890"

are not aligned properly making it look very odd

I would to fix these UI issues

### Add ScreenShots

![Screenshot 2024-10-18 202324](https://github.com/user-attachments/assets/2743a8ae-a6f4-4b5e-aa65-f85d135674eb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuprHUlk** [comment]
@SUGAM-ARORA can you please assign it to me.

**Comment by SUGAM-ARORA** [comment]
@SuprHUlk Issue assigned to you
