### ISSUE TITLE
Feat: Improve the UI of read more page

### ISSUE THREAD

**Issue by SuprHUlk** [SUGAM-ARORA/UniCollab#822]
### Describe the feature

Currently,  the read more page's UI looks very static with no style. I would like improve/update the UI.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a5e25cfd-aace-45a6-8fba-f35a9c730a77)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SUGAM-ARORA** [comment]
@SuprHUlk Issue assigned to you
