### ISSUE TITLE
[FEATURE] Implement a 'Settings' Page

### ISSUE THREAD

**Issue by yashmandi** [SUGAM-ARORA/UniCollab#84]
**Is your feature request related to a problem? Please describe.**
In the left sidebar, I can see the 'Settings' icon, but on clicking on it nothing happens. It should route to a 'Settings' Page where the user can change/modify their settings.

**Describe the solution you'd like**
I would like to create an entire 'Settings' Page, which on clicking on settings icon, it will route to that page.

**Additional context**
Would like to work on this feature under GSSoC '24. Request you to assign this task to me :)

**Comment by SUGAM-ARORA** [comment]
@yashmandi Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged
