### ISSUE TITLE
Add Visual Indication for Active Search Bar and Typing

### ISSUE THREAD

**Issue by ojasvi004** [SUGAM-ARORA/UniCollab#85]
When the search bar is clicked, there should be a visual indication to show that it is in use. This could be a change in color, border or any other visual cue. 
Additionally, there should be a similar indication while typing to enhance the user experience. 

@SUGAM-ARORA, please assign this issue to me under GSSOC'24.

**Comment by SUGAM-ARORA** [comment]
@ojasvi004 Issue assigned to you
