### ISSUE TITLE
[Bug]: The end of navbar icons is not display

### ISSUE THREAD

**Issue by SrinivasDevolper** [SUGAM-ARORA/UniCollab#89]
**Describe the bug**

The end of the **navbar icons** is not visible from the tablet view below the section

**Expected behavior**

Icons are visible in below tablet view

**Screenshots**

actual behavior:-
![unicollab img1](https://github.com/SUGAM-ARORA/UniCollab/assets/121508628/0f6be57b-9a65-42da-a09b-0f321de81d56)

expected behavior:-
![unicollab img2](https://github.com/SUGAM-ARORA/UniCollab/assets/121508628/bebcfdeb-1906-489c-a4ab-aa014f109922)

**Additional context**

**I am GSSOC24 Contributor**
please assign me, I would like to work on that

**Comment by SUGAM-ARORA** [comment]
@SrinivasDevolper Issue assigned to you

**Comment by SrinivasDevolper** [comment]
Thanks for assigned this issue

**Comment by Ankitamishra17** [comment]
please assign this issue to me under GSSoC'24.

**Comment by SrinivasDevolper** [comment]
> @SrinivasDevolper Issue assigned to you

Now it's fine, The end of the navbar icons is visible
