### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by Jagpreet153** [SUGAM-ARORA/UniCollab#96]
**Is your feature request related to a problem? Please describe.**
Yes, Making a about us page will allow user to be more familiar with the website

**Describe the solution you'd like**
I would be making the about us section which would be directed through the footer button

**Describe alternatives you've considered**
The section would be fully responsive along with matching UI

**Additional context**
Kindly assign this task to me under GSSoC'24

**Comment by SUGAM-ARORA** [comment]
@Jagpreet153 Issue assigned to you

**Comment by SUGAM-ARORA** [comment]
Merged
