### ISSUE TITLE
Integration of login page

### ISSUE THREAD

**Issue by Venkatknight2295** [SUGAM-ARORA/UniCollab#99]
**Is your feature request related to a problem? Please describe.**
There is no  login page for the users to login
**Describe the solution you'd like**

**Describe alternatives you've considered**
we have to upload a login page so that users login there creds
**Additional context**
like this 
![image](https://github.com/SUGAM-ARORA/UniCollab/assets/118790430/2637fc38-7d10-4a0d-b74c-51d8eebf121a)

**Comment by SUGAM-ARORA** [comment]
@Venkatknight2295 Issue already exists #18 . But we can wait for more and see how issue goes on then will assign this to you. Moreover if you want you can work on this issue. But I won't assign this to you at the moment. If no work goes there then will assign you by end of the week.

**Comment by Venkatknight2295** [comment]
I HAVE ALREADY MADE CREATE  AN ACCOUNT PART ONLY SIGNIN IS LEFT ONCE YOU ASSIGN I WILL MAKE THAT AND PUSH

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA I HAVE ALREADY MADE CREATE AN ACCOUNT PART ONLY SIGNIN IS LEFT ONCE YOU ASSIGN I WILL MAKE THAT AND PUSH

@Venkatknight2295 Are you up for this??

**Comment by Venkatknight2295** [comment]
@SUGAM-ARORA YES

**Comment by SUGAM-ARORA** [comment]
@Venkatknight2295 Issue assigned to you
